### ISSUE TITLE
PPSSPP screen error in ppsspp game on daijisho

### ISSUE THREAD

**Issue by Mighty27** [TapiocaFox/Daijishou#179]
i found a bug in psp on daijisho....
ppsspp screen is error if i select game psp from daijisho but in ppsspp is working properly and in this case i download gold ppsspp from google play

![Screenshot_2023-01-10-10-14-27-453_com magneticchen daijishou](https://user-images.githubusercontent.com/81411396/211453946-9f2c618a-d0c0-4060-bba7-d77af111edf4.jpg)
![Screenshot_2023-01-10-10-14-37-519_org ppsspp ppssppgold](https://user-images.githubusercontent.com/81411396/211453953-ec470584-2777-4303-a330-143ee59b4189.jpg)

**Comment by magneticchen** [comment]
Sorry but I could not replicate the problem. Are this problem still happening?

**Comment by AgentlReal** [comment]
Yeah i think its a bug. I have the same problem by using PPSSPP Gold. The screen is cropped in the corner whenever i launch a PPSSPP game via daijisho
