### ISSUE TITLE
Impossible to select languages in ScummVM

### ISSUE THREAD

**Issue by ghiki** [TapiocaFox/Daijishou#262]
Hi, I tried to add some multi-language games from Retroarch ScummVM core, and when I scan from there, it appears option to select multiple language if the game supports it and to play in these languages:
![Screenshot_20230226-233404](https://user-images.githubusercontent.com/854302/221442035-34bf1257-bb18-4d79-a64d-793fa7d55d49.png)

But if I launch the game form Daijisho, the game starts on It's main language and it isn't possible to change it:

![Screenshot_20230226-233419](https://user-images.githubusercontent.com/854302/221442080-022a118d-7ae5-4772-a0d8-d51cd280128c.png)
![Screenshot_20230226-233439](https://user-images.githubusercontent.com/854302/221442086-33689c8f-d5dc-4d18-8c6c-65145919649e.png)

If the game was launched and I've go to ScummVM core menu (Start>Return to menu), I can see the configs in "scummvm.ini" file, and if I launch the game from this menu, It respects what is configured in .ini file

![Screenshot_20230226-233512](https://user-images.githubusercontent.com/854302/221442135-555a2b49-1d1d-4686-9c18-a7c653ba5085.png)
![Screenshot_20230226-233645](https://user-images.githubusercontent.com/854302/221442139-587af878-c252-4c80-8dd2-b3367574467e.png)

**Comment by magneticchen** [comment]
I have no idea with this issue.

**Comment by ghiki** [comment]
I dont know if it's possible to call what retroarch calls from it's menu to set the language but from daijisho (like intent), and if it's possible, to make Daijisho to identify games (like RA does)

**Comment by magneticchen** [comment]
Unfortunately Dai cannot practically analyze the language of the game. So this probably need to be fixed by RA.

**Comment by Jetup13** [comment]
Going back to this old issue to explain how you select languages when launched from a frontend.

We'll use Drascula The Vampire Strikes Back (CD DOS, Multilanguage) as an example

1. Add the game to ScummVM via RetroArch:

> RetroArch > Load Core > ScummVM > Add Game > Locate folder > Choose > Add Each Language

2. Write down the ScummVM ID it gives you for the different languages

For example Drascula The Vampire Strikes Back (CD DOS, Multilanguage) in French was:

> drascula-fr

3. Create a .scummvm file with that ScummVM ID as a line

4. Place the .scummvm file within the content folder 

It should now launch with that language. You *must* do step one. Sorry for the ultra late solution. I don't ScummVM games but after testing it worked for me
