### ISSUE TITLE
Game preview display problem

### ISSUE THREAD

**Issue by sunydo** [TapiocaFox/Daijishou#291]
Exit the game every time，Don't show game preview
Version 1.4.7

**Comment by sunydo** [comment]
sorry，version 1.4.9
![04F20AA7FFAA140747C586691DFF5EA1](https://user-images.githubusercontent.com/63689398/224466125-c8271f90-478d-4671-acbd-2776d17563fa.png)

**Comment by magneticchen** [comment]
Sorry could you explain more explicitly.

**Comment by sunydo** [comment]
sorry，Version 1.4.9
![04F20AA7FFAA140747C586691DFF5EA1](https://user-images.githubusercontent.com/63689398/224478805-247f91d4-2cab-4e0b-b9ae-0540b389f186.png)
Every time I quit the game
There will be a game that does not display the game cover

**Comment by magneticchen** [comment]
Thanks for the report. If you can help open the logger and check any crashed related to images would be helpful. Thanks!

**Comment by sunydo** [comment]
![IMG_0936](https://user-images.githubusercontent.com/63689398/224491512-24b6e95
![IMG_0937](https://user-images.githubusercontent.com/63689398/224491517-27cabfac-93b1-41a0-811f-170ed2c96832.JPG)
7-5ae7-47b2-bb1d-dc8c392c2b60.JPG)
Thank you！

**Comment by sunydo** [comment]
![IMG_0936](https://user-images.githubusercontent.com/63689398/224491686-1a8218b2-3ff1-4bce-8ed4-dbed4c0f51d5.JPG)
Thank you！

**Comment by magneticchen** [comment]
Sorry but you have to find the ones with `bitmap`, `image` etc.

**Comment by sunydo** [comment]
Sorry i can't find the ones with bitmap, image....
