### ISSUE TITLE
Support for SteamGridDB scraping

### ISSUE THREAD

**Issue by DFelten** [TapiocaFox/Daijishou#345]
Thanks for your great launcher. This is simply the best currently available for Android :)

Could you please add the [SteamGridDB](https://www.steamgriddb.com) as database for scraping images? This is now a huge library of retro games as well, as it is used for the Steam Deck. For example, RPG Maker games that are otherwise not found are also included here.

**Comment by magneticchen** [comment]
Hello. I've looked into the site you've mentioned. It is decent however. It lacks of some features that Dai required.
1. Unified aspect ratio for each platform.
2. A search function that can filtered by each platform.

**Comment by DFelten** [comment]
Thanks for the answer. You're right, there is only one aspect ratio for each media type since they were created for Steam. It is also only possible to search for games and then for a game the respective media types. There are no other platforms as far as I can see.

Therefore, this would probably have to be a separate scraper that can be used for all systems. The images would be scaled or cropped. Unless you set a different apsect ratio once SteamGridDb is used.

By the way, here are the resolutions of each type: https://www.steamgriddb.com/upload

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/501
