### ISSUE TITLE
Intellivision games not gecognized 

### ISSUE THREAD

**Issue by zedman18** [TapiocaFox/Daijishou#380]
I have some intellivision games that are not recognized only one game and that is a .rom file, the other game are .int files. Am I doing something wrong? In Retroarch they work smoothly.

Thanx for the help btw.

**Comment by magneticchen** [comment]
Please make sure that those files have different hashes.

**Comment by telanus** [comment]
Same problem here. The No-intro romset all have int suffix, and tried it tonight and it is not picked up by the frontend

**Comment by NixieLake** [comment]
Same problem here. I'm using No-Intro romset in .zip files. They work in Retroarch without problem but Daijisho is not picking up any of them at all.

**Comment by NixieLake** [comment]
I found a workaround.

You have to view the players and edit the regex to include the extension on your roms. Then they should scrape normally.
