### ISSUE TITLE
Use screenscraper.fr for scraping.

### ISSUE THREAD

**Issue by smb1982x** [TapiocaFox/Daijishou#389]
Please add support for scraping using free and premium accounts from https://screenscraper.fr 

Free accounts can scrape up 5000 media per day with 1 thread, with premium accounts being able to scrape up to 100,000 media per day with up to 10 simultaneous threads!

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/194#issuecomment-1440150563
