### ISSUE TITLE
USB sticks games problem 

### ISSUE THREAD

**Issue by Tomcoding75** [TapiocaFox/Daijishou#395]
Hi,
At first. I live your app, so great. Congratulations!!!

I have a microsd of 2to with some roms. I plged it with 2 differents sticks.
The app recognize it and scan All the roms in the  path.
The problem is that he had displayed only few roms not all of them.
Do you know why and how to fix it?

I use the last version of Daijishou on Android Huawei

Thx

**Comment by Tomcoding75** [comment]
I did a new test with various system. For example SegCD, I have 203 roms, He scan all of them but list and scrape only 30 of them.

**Comment by Tomcoding75** [comment]
It's come from my sd card. Just a crap one!

**Comment by TapiocaFox** [comment]
#162
