### ISSUE TITLE
Missing Retroarch cores

### ISSUE THREAD

**Issue by SegAgeS** [TapiocaFox/Daijishou#415]
Some cores are missing using 64bit retroarch.  Can't find mame 2003 core needed to run certain roms

**Comment by Jetup13** [comment]
[Mame 2003](https://github.com/TapiocaFox/Daijishou/blob/main/platforms/MAME.json#L36) is already available as a player. If your missing it try redownloading the MAME platform

> Download > Arcade (MAME) > Import

**Comment by SegAgeS** [comment]
Its available within Mame arcade but not fbneo which is the rom pack I downloaded.  I have the folder imported as fbneo arcade and mame 2003 isn't available as a core
