### ISSUE TITLE
Horizontal list of platforms does not fill full width of area under platform wallpaper when in kiosk mode

### ISSUE THREAD

**Issue by RYJASM** [TapiocaFox/Daijishou#424]
The horizontal list of platforms should fill the full width of the area below the wallpaper of the platform when in kiosk mode.

Right now when switching to kiosk mode, the horizontal list does not fill the area where the download button was. It looks out of place and broken and hides platform names unnecessarily.

**Comment by TapiocaFox** [comment]
Sorry but it is designed that way deliberately.
