### ISSUE TITLE
Move apps tab/page to be it's own android platform page

### ISSUE THREAD

**Issue by RYJASM** [TapiocaFox/Daijishou#426]
I would prefer less clutter - to remove all of the top tabs/categories.

By removing apps/genre tabs/categories and then moving the settings tab to an icon in the top right (like how the sync button works) would be perfect.

I want to be able to just press left and right on a dpad and swap between platforms. Right now the app is very heavy with the number of button presses required to get to a game.

**Comment by TapiocaFox** [comment]
Duplicated. #37
