### ISSUE TITLE
Unable to launch PPSSPP activity after emulator update

### ISSUE THREAD

**Issue by arutemu** [TapiocaFox/Daijishou#430]
After PPSSPP was updated to version 1.14.3 the app broke shortcuts, and also old command to launch a game with PPSSPP stopped working and throwed an error.

The old command:
```
-n org.ppsspp.ppsspp/.PpssppActivity
  -a android.intent.action.VIEW
  -d {file.uri}
  --activity-clear-task  --activity-clear-top  --activity-no-history
```
The error:
`android.content.ActivityNotFoundException: Unable to find explicit activity class {org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?`

[After discussing the issue with PPSSPP devs](https://github.com/hrydgard/ppsspp/issues/17416) the issue was fixed in updates 1.15.3, but also now the command to run the emulator is changed a bit.
The command that works for me with the last PPSSPP now is:
```
-n org.ppsspp.ppsspp/.PpssppActivity 
-a android.intent.action.VIEW 
-c android.intent.category.DEFAULT
-d {file.uri} 
-t application/octet-stream
--activity-clear-task  --activity-clear-top  --activity-no-history
```

**Comment by Jetup13** [comment]
Thanks, I've update the launch argument for both PPSSPP and PPSSPP gold. #431
