### ISSUE TITLE
Duckstation

### ISSUE THREAD

**Issue by dIEnigma93** [TapiocaFox/Daijishou#435]
Duckstation doesn't load games.

**Comment by Jetup13** [comment]
You need the following to launch games:

Latest Duckstation:

[Google Play](https://play.google.com/store/apps/details?id=com.github.stenzek.duckstation) or [Duckstation website](https://www.duckstation.org/android/)

Duckstation/Daiji needs permissions to the same psx folder as Daijishou

4. Update psx platform via Daijishou

> Daijishou > Download > Sony Playstation > Import

Or if you want Daijishou to update upon starting

> Daijishou > Settings > Library > Update Platforms Automatically

**Comment by dIEnigma93** [comment]
This was really helpful! Works like a charm. Any tips for Redream? It launches to the app as opposed to the game
