### ISSUE TITLE
Dsi

### ISSUE THREAD

**Issue by Kmog2185** [TapiocaFox/Daijishou#439]
Could you add Dsiware as a platform?

**Comment by Jetup13** [comment]
Unfortunately DSiWare can't be launched directly, even from MelonDS/RetroArch. 

For those uninitiated DSiWare must be launched within DSi bios:

> Install DSiWare game to nand > Launch DSi BIOS > Scroll to installed game

**Comment by EgoBizarro** [comment]
> Unfortunately DSiWare can't be launched directly, even from MelonDS/RetroArch.
> 
> For those uninitiated DSiWare must be launched within DSi bios:
> 
> > Install DSiWare game to nand > Launch DSi BIOS > Scroll to installed game

Huh, weird. Now it doesn't work anymore. I had it working on March, though.
