### ISSUE TITLE
Citra Canary support

### ISSUE THREAD

**Issue by TiagoSLoureiro** [TapiocaFox/Daijishou#446]
Hello there,

There doesn't seem to be a Citra Canary on the default players of Daijisho.
There is a RetroArch Citra Canary, but not the stand alone one.

Am I missing something?
Thanks!

**Comment by iamkalax** [comment]
There will be an update with the new player for the new canary vulkan build soon, I'm assuming.

**Comment by luke-70it** [comment]
I tryied to manually configure Citra canary, but it doesn't work.
I used these settings:
-n org.citra.citra_emu.canary/org.citra.citra_emu.activities.EmulationActivity
  -a android.intent.action.VIEW
  -e GamePath {file.path}
  --activity-clear-task
  --activity-clear-top 

When I try to start a game, I see a popup message: "Permission Denial: starting..."

**Comment by mjkaye** [comment]
I believe this was fixed by https://github.com/TapiocaFox/Daijishou/commit/a49248f03665184cf2901d78d2fc99a9fd6c4e20 @Jetup13?

The `Permission Denial` error was fixed by https://github.com/citra-emu/citra/pull/6996

**Comment by Jetup13** [comment]
Yes this was added, forgot to close this issue~~~
