### ISSUE TITLE
how to send my theme i made .

### ISSUE THREAD

**Issue by sikama10** [TapiocaFox/Daijishou#454]
hello, how to contact the founder of daijishou I have a theme to send them that I have done all the platforms done

need help for contact founder daijishou tank ! this is my first theme

![Screenshot_20230525-173633](https://github.com/TapiocaFox/Daijishou/assets/38733584/0ca0b748-bb64-4ddb-8b83-f23bff3cbbbe)
![Screenshot_20230525-173650](https://github.com/TapiocaFox/Daijishou/assets/38733584/e04b0501-83c8-4ed6-8c33-1cb5bcfac848)
![Screenshot_20230525-173701](https://github.com/TapiocaFox/Daijishou/assets/38733584/32ea93f8-dede-4619-ab4b-79ab44aee865)
![Screenshot_20230525-173716](https://github.com/TapiocaFox/Daijishou/assets/38733584/bc0b7f9a-614e-4fd0-af9c-43df6b087c7f)
![Screenshot_20230525-173725](https://github.com/TapiocaFox/Daijishou/assets/38733584/af0082ea-733d-4cf4-92fb-459e92e9cec7)
![Screenshot_20230525-173742](https://github.com/TapiocaFox/Daijishou/assets/38733584/ef8f6504-2729-43ee-9499-473c740effd4)
![Screenshot_20230525-173751](https://github.com/TapiocaFox/Daijishou/assets/38733584/b438471f-0dfe-49ab-8669-6bcb854e67a4)
![Screenshot_20230525-173806](https://github.com/TapiocaFox/Daijishou/assets/38733584/8f1acb73-60ff-498a-939d-34418d83deb7)
![Screenshot_20230525-173819](https://github.com/TapiocaFox/Daijishou/assets/38733584/3d233d48-25c5-43e9-b95b-d6048a0c38ba)

![Screenshot_20230525-171323](https://github.com/TapiocaFox/Daijishou/assets/38733584/22f1d4e3-5761-41ef-86e4-211424e42127)
![Screenshot_20230525-171331](https://github.com/TapiocaFox/Daijishou/assets/38733584/78b7f6f9-6d65-443b-af4a-b84a927c6589)
![Screenshot_20230525-171340](https://github.com/TapiocaFox/Daijishou/assets/38733584/bebb1b31-7443-4bd8-94a5-553839a38cd4)
![Screenshot_20230525-171348](https://github.com/TapiocaFox/Daijishou/assets/38733584/89a4039b-a9bb-457e-9e1b-7c03a2a5c795)
![Screenshot_20230525-173558](https://github.com/TapiocaFox/Daijishou/assets/38733584/fc46777c-9e5f-4863-a66a-f9d41b845a70)
![Screenshot_20230525-173612](https://github.com/TapiocaFox/Daijishou/assets/38733584/09b38ed6-90e4-4469-964c-bc2293ca55ff)
![Screenshot_20230525-173620](https://github.com/TapiocaFox/Daijishou/assets/38733584/836c5330-ddc8-4733-bc00-d55472b6a37a)

**Comment by Post-Mortem** [comment]
Hey dude, very cool work. Please join the official discord server here:
https://discord.gg/exbs98vR

Then go to the appearance category and write to me  (post mortem) so i can help you.
