### ISSUE TITLE
Front-end crash bug in version 1.4.56

### ISSUE THREAD

**Issue by sunydo** [TapiocaFox/Daijishou#455]
Hello, I’ve discovered a critical bug in the latest update. I am currently using an Android 9 system and have updated daijishou to version 1.4.56. Whenever I long-press the “A” button on my game controller in the game list within the front-end, the application crashes abruptly. This issue was not present in the previous version.

**Comment by sunydo** [comment]
https://github.com/TapiocaFox/Daijishou/assets/63689398/84c291c7-a24e-49fe-aae8-467c2ac4b176

**Comment by TapiocaFox** [comment]
Could you please enable the debug mode. And capture the crash logs for me? Thanks.

**Comment by sunydo** [comment]
![27012600](https://github.com/TapiocaFox/Daijishou/assets/63689398/33621e2e-62bf-44bd-941d-7f89e09570db)
![27012632](https://github.com/TapiocaFox/Daijishou/assets/63689398/7d6ddfcb-c0ce-48b7-9506-cf275b0ddfcb)
![2716](https://github.com/TapiocaFox/Daijishou/assets/63689398/e2a05a5c-3bf9-4c99-bfbb-2ca1af9cc614)

**Comment by TapiocaFox** [comment]
Could you copy paste the one with prohibit icon (Red one). Thanks for the cooperation.

**Comment by TapiocaFox** [comment]
Hello. It seems like RetroAchievements is causing issues. Please update to our latest release. That should resolve the issues.

**Comment by sunydo** [comment]
great,the bug has been fixed after the update ,thank you!
