### ISSUE TITLE
problems with retroachievement. 

### ISSUE THREAD

**Issue by Semn400** [TapiocaFox/Daijishou#457]
In the last update whenever I try to put my credentials in the app it either doesn't recognize it or it just closes

Edit more complete:

when I enter the retroachievement tab and enter my data I confirm that the app simply closes or does not compute. even connected to the website. Sending 

https://github.com/TapiocaFox/Daijishou/assets/135095385/cd4c97ed-644b-49fa-aed6-1088a2afb48a

note: the app is already in the latest version and has no connection problems

**Comment by TapiocaFox** [comment]
Could you elaborate more specifically. Are there any screenshots you can illustrate that. Thanks.

**Comment by andiweli** [comment]
You mean Daijisho crashes (=closes)? Thats the issue for me with 1.4.59.

**Comment by stuffu** [comment]
I also still have the issue with 1.4.59, no crash but a message that credentials are wrong.

**Comment by TapiocaFox** [comment]
Did that fixes in 1.4.60?

**Comment by stuffu** [comment]
My bad, it was .60 I tried. Unfortunately, no it didn’t…

**Comment by TapiocaFox** [comment]
Can you show me the message you were saying?

**Comment by stuffu** [comment]
> Can you show me the message you were saying?

Here is what it looks like.

![IMG_2751](https://github.com/TapiocaFox/Daijishou/assets/4310040/6eb7eecc-35d2-4b09-9ba3-a319992570e8)

**Comment by TapiocaFox** [comment]
Sorry. But that is not related to Daijishō, it is the problem of retroarch itself.

**Comment by stuffu** [comment]
Thanks for the new update, just tried it and unfortunately it still doesn’t register games played. Can I help with troubleshooting in some way?

**Comment by TapiocaFox** [comment]
> @TapiocaFox 
> 
> Thanks for the new update, just tried it and unfortunately it still doesn’t register games played. Can I help with troubleshooting in some way?

I have no idea if that stuff happened on retroarch. You have to figure it out whether your configuration in retroarch is correct instead of daijishō based on the message you've shown.

**Comment by stuffu** [comment]
@TapiocaFox 

I have disabled it in retroarch and I am just using the built in retro achievement function now. Just tried a new game which is not being registered as played or gives any sign of unlocking achievements , checked that it had achievements as well.

**Comment by TapiocaFox** [comment]
> @TapiocaFox
> 
> I have disabled it in retroarch and I am just using the built in retro achievement function now. Just tried a new game which is not being registered as played or gives any sign of unlocking achievements , checked that it had achievements as well.

Sorry I have no idea what you were talking about at this point. Would you please start new issue that fully elaborate your issues thanks.
