### ISSUE TITLE
Immediate crashes of App with 1.4.59

### ISSUE THREAD

**Issue by andiweli** [TapiocaFox/Daijishou#459]
Hello!

Anbernic RG405M here running @ Android 12.
Daijisho 1.4.58 worked without problems.
1.4.59 crashes after a few seconds. Reloading shows the same error. It is not useable.

Workaround: Deactivate WiFi on the device. So it has something to do with internet connection inside the app.
I have Retroarchivements activated, perhaps thats the culprit... thats the last the log shows before crashing.

Kind regards
Andreas

**Comment by TapiocaFox** [comment]
Thanks for the report. Seems like it is retroarchievements issues. Sorry for the inconveniences. I will publish a new release as soon as possible.

**Comment by andiweli** [comment]
Thank you! Working perfectly now again 😉Am 31.05.2023 um 16:15 schrieb タピオカ狐 ***@***.***>:﻿
Hello. The latest release should fix the issue.

**Comment by TapiocaFox** [comment]
Thanks for the report!
