### ISSUE TITLE
ScummVM platform doesn't find any games

### ISSUE THREAD

**Issue by andiweli** [TapiocaFox/Daijishou#460]
Strange issue here...
21 platforms installed
One of it is "ScummVM"
I have all my games in separate directories on the microSD /scummvm/sky ... /scummvm/monkey1 and so on.

I select /scummvm as directory > empty, no games found.
If I select any of the game folders inside the scummvm-directory > no games found.

ScummVM (the app) has no problem finding and recognizing them.
Also finding games with other platforms and directories works without problems.

Any idea what I am doing wrong?
Thanks.

**Comment by Max593** [comment]
I'm experiencing the same issue, this is the only platform with this kind of behavior so far.

**Comment by Post-Mortem** [comment]
> Strange issue here... 21 platforms installed One of it is "ScummVM" I have all my games in separate directories on the microSD /scummvm/sky ... /scummvm/monkey1 and so on.
> 
> I select /scummvm as directory > empty, no games found. If I select any of the game folders inside the scummvm-directory > no games found.
> 
> ScummVM (the app) has no problem finding and recognizing them. Also finding games with other platforms and directories works without problems.
> 
> Any idea what I am doing wrong? Thanks.

Did you manage to solve this issue? If not, can you reply with the file format of your rom files?

**Comment by Jetup13** [comment]
Regex adds .scummvm files as mentioned in the [wiki](https://github.com/TapiocaFox/Daijishou/wiki/Players-and-File-Extensions#scummvm)

Scummvm files contain the games scummvm id within the file. You can read about it [here](https://docs.libretro.com/library/scummvm/#running-a-game)
