### ISSUE TITLE
compressed file support

### ISSUE THREAD

**Issue by kid1412621** [TapiocaFox/Daijishou#462]
currently I got several zip files of PSP ROM. They're not be recognized by Daijisho unless I decompress them.

**Comment by Jetup13** [comment]
PPSSPP doesn't support loading games from zip. Decompress it. If you're worried about saving space you can convert PSP games to cso format.

**Comment by kid1412621** [comment]
> PPSSPP doesn't support loading games from zip. Decompress it. If you're worried about saving space you can convert PSP games to cso format. 

But RetroArch - PPSSPP supports scan and play zip file.

**Comment by Jetup13** [comment]
It's not worth the hassle to use zips for disc based games. If core crashes, which PPSSPP certainly does at times, it will not clear the cache folder. RetroArch unzips the files to a cache folder, plays the first file it finds (optical disc games for systems like PSX & Sega CD will have problems), & delete cache afterwards when content is closed (wouldn't that cause wear SD cards?)

This is why stuff like CHD and CSO exist. Convert your games if you want to prevent possible future problems & save on space. But if you do want it you can simply add it to the playler

> Daijishou > Settings > Library > Inspect Player > select the player > add zip to Player accepted filename regex > Save

**Comment by kid1412621** [comment]
> It's not worth the hassle to use zips for disc based games. If core crashes, which PPSSPP certainly does at times, it will not clear the cache folder. RetroArch unzips the files to a cache folder, plays the first file it finds (optical disc games for systems like PSX & Sega CD will have problems), & delete cache afterwards when content is closed (wouldn't that cause wear SD cards?)
> 
> 
> 
> This is why stuff like CHD and CSO exist. Convert your games if you want to prevent possible future problems & save on space. But if you do want it you can simply add it to the playler
> 
> 
> 
> > Daijishou > Settings > Library > Inspect Player > select the player > add zip to Player accepted filename regex > Save

Cool, thx for explanation.

**Comment by kid1412621** [comment]
hi @Jetup13, one more question, why psp player doesn't support CHD by default?

**Comment by Jetup13** [comment]
You would have to direct that question to PPSSPP's devs. It's been requested years ago. [Here's the issue ticket](https://github.com/hrydgard/ppsspp/issues/10417)
