### ISSUE TITLE
Can a new system for apple2 be created?

### ISSUE THREAD

**Issue by carlosdesedas** [TapiocaFox/Daijishou#478]
Hi.. I lack the skills to add a JSON for enabling using .dsk images of an apple 2 system being emulated by Apple2ix.  can this JSON be created and added?  I think Apple2ix is the only emulator you can sideload to android and emulate apple 2 games nicely...

**Comment by Jetup13** [comment]
Does Apple2ix support loading from frontends?

There use to be a RetroArch core for Apple2 long ago but that's long gone. And I'm pretty sure the Android MAME core doesn't have MESS components to load apple 2 games

**Comment by mcwild77** [comment]
Android MAME is capable of loading Apple II games via MESS but it requires a horrific setup, which I listed up here. Note that this worked on my Samsung A53, but didn't work when I repeated the process on my Odin Lite.
https://www.reddit.com/r/RetroArch/comments/10b81io/new_multi_mess_current_core_for_64bit_android/

So yeah, you can boot floppy disks theoretically (I am still struggling on booting hard disk images like Total Replay), but I have no idea how you'd pass it off via Daijisho.
