### ISSUE TITLE
Hide unwanted app icons in "Apps" tab

### ISSUE THREAD

**Issue by Slim08** [TapiocaFox/Daijishou#482]
Could you add an option to hide unwanted app icons from the "Apps" tab like system apps which can't be uninstalled or apps that run in the background and don't need to have an app icon present all the time. Same as marking apps as "Games" with one global "show hidden apps" button for access if needed. Just for ease of use.

Thank you

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/93
