### ISSUE TITLE
Unable to launch roms using mame

### ISSUE THREAD

**Issue by npaladin2000** [TapiocaFox/Daijishou#489]
Same roms launch when loaded through RetroArch but when selecting "mame" in Daijisho (which I assume to mean "mame-current" RetroArch freezes and has to be killed.

**Comment by Jetup13** [comment]
Select mamearcade and see if it launches.

I might need to delete the `mame - RetroArch - mame` entry as that seems like it's no longer available on Android (or wasn't ever)

**Comment by npaladin2000** [comment]
Yeah, thinking mamearcade could stand renaming to mame-current too, to match the core name?

**Comment by Jetup13** [comment]
If I follow the typical naming scheme for Daijishou RetroArch players its correctly named as mamearcade. As with other cores the player entry is named after the filename which is `mamearcade_libretro_android.so`

Plus there's no core named Mame current on Android. At least not anymore?

**Comment by npaladin2000** [comment]
It's listed as MAME - Current in the RetroArch UX, which more people are going to see than the filename.

**Comment by Jetup13** [comment]
Sounds like you haven't updated the core info files. 

Here's the [current info file](https://github.com/libretro/libretro-super/blob/master/dist/info/mamearcade_libretro.info). It was recently updated (March 10th)

You can update the core info files via RetroArch

> RetroArch > Online Updater > Update Core Info Files

You might need to exit RetroArch for it to update the info file cache if it's enabled.

Either way, I need to delete the mame - RetroArch - mame player entry when I can

**Comment by npaladin2000** [comment]
Actually, now it's just called MAME...so yeah, deleting the existing Retroarch - MAME entry would be wise, and after that, renaming "mamearcade" to "mame" would probably make sense.  But at the very least that existing mame entry needs to go away.

**Comment by Jetup13** [comment]
[Updated](https://github.com/TapiocaFox/Daijishou/commit/a9bc861d2d12a082af15ba8a6bfe03973c83fb14) to remove unused entries

**Comment by Jetup13** [comment]
Its now under `mame - Retroach - mame`
