### ISSUE TITLE
Backups location

### ISSUE THREAD

**Issue by 31337-4554551n** [TapiocaFox/Daijishou#491]
Where do the backups go?

Daijisho insists on google drive access permissions in order to set them up, but then doesn't actually back anything up to google drive.

The restores are compatible across devices.

Is the data going to some other server owned by daijisho? In which case, can we get some details, and why does it need access to google drive?

I tried having a look at the code, only to note that the repo is just assets, not the actual code for the APK

**Comment by Post-Mortem** [comment]
This is not an issue with Daijisho, please use our discord server for questions about the app.  Here: https://discord.com/channels/965270127312535592/965286290813759488
