### ISSUE TITLE
Manual scraped images support

### ISSUE THREAD

**Issue by lordelan** [TapiocaFox/Daijishou#497]
We edit **a single game** to change/add a custom boxart image but we can't access the images that Daijishou downloads upon scraping because they are stored in /data/user/0 which is annoying.

Either one of the following two approaches would help **a lot** to enable users to use their own scraped images for whole rom sets that they already scraped on a PC with Skraper or anything like that, given the filename of the image matches the rom name:

1. Place the scraped images in the user accessable internal memory in /emulated/0/Android/... instead of placing it in the root directory /data/user/0 so we can see how they are named and can copy in our own images whenever needed
2. Keep the Daijishou images where they currently are **but** give us the option to define an own directory per system where we could place our images in and whenever an image is found in our own directory, it will be used while the one scraped by Daijishou (if it exists) will only work as a fallback.

This is especially important for homebrew games (like from itchio) and rom hacks (which is the main reason I'm complaining about this).

**Comment by Jetup13** [comment]
You can already replace entire platform of images as long as the image name is the same as the rom

> Daijishou > Highlight Platform > 🖊️ > Import Preview Media > Select folder with images
