### ISSUE TITLE
Gameboy json needs updated

### ISSUE THREAD

**Issue by DroidlyMobileGames** [TapiocaFox/Daijishou#506]
The Gameboy and Gameboy color json need to be updated to file.uri instead of file.path otherwise you gave me some content to share on the channel to temporarily fix this.  😁

**Comment by DroidlyMobileGames** [comment]
Oh note this is for the MyOldBoy emulator

**Comment by Jetup13** [comment]
Update in [2079907](https://github.com/TapiocaFox/Daijishou/commit/2079907293d2f2deed4753f720891c2d8163d186). Thanks

**Comment by DroidlyMobileGames** [comment]
Awesome!  Any thoughts on adding Android as a platform to the main
platforms?  Idea I had is to have an option to select games into a list and
the icon would just be the game icon.  Glad to know you're active still as
well, I find your front end to be perfect now you just need a custom gaming
device to go along with it 😊

**Comment by Jetup13** [comment]
You can already add [Android to Platforms](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#adding-android-platform)

**Comment by DroidlyMobileGames** [comment]
Oh man that's awesome I didn't even notice this even after using your app
for almost a year 😆.  As a fellow developer myself I always think of other
things to change/add hense why I noticed the json files not being updated.
Anyways thank you again, I again love your work you did a great thing with
this front end!

Below is my review from last year 😁 still back it!
