### ISSUE TITLE
Video Previews not working

### ISSUE THREAD

**Issue by ScottyBandicoot** [TapiocaFox/Daijishou#515]
I noticed when I first start using Daijishou, video previews worked within the details section of each game. Now, video preview does not work. The option is still turn 'on' in the menu. The only thing that has changed is I have more platforms and games. restarting and flipping the option off and on does not fix the video previews. Could there be a different setting (in android) that I need to check? I am on a Retroid Pocket 3+. Using the current version of Daijishou from the Google Play Store.

**Comment by Odinuser4200** [comment]
I am having the same issue. I see nothing  covering this issue videos not playing anymore and it's very frustrating. Someone please help!!

**Comment by Jetup13** [comment]
Video previews now working correctly as of update 396

Closing issue
