### ISSUE TITLE
Additional System

### ISSUE THREAD

**Issue by Kmog2185** [TapiocaFox/Daijishou#518]
Would you be able to add iOS as a platform to Daijisho, with TouchHLE available as a player?

**Comment by Jetup13** [comment]
I gave touchHLE a try and it doesn't seem like it supports launching games/apps from a frontend or adb session. Another hurdle it requires ipa files to be placed in a directory where Daijishou can't select:

> Android\data\org.touchhle.android\files\touchHLE_apps\ 

As of this time, no, you can't make it as a selectable platform/player
