### ISSUE TITLE
Button issue.

### ISSUE THREAD

**Issue by Apecer3310** [TapiocaFox/Daijishou#527]
In game, I can still use it but at the "platforms" L2 supposed to go left and R2 go right. Somehow my L2 button doesn't work on daijishou. Is doesn't go left. 

https://github.com/TapiocaFox/Daijishou/assets/144093794/33e0f0ca-d95e-4859-93e6-ba636dce18c2

**Comment by TapiocaFox** [comment]
Hello. Your L2R2 is probably analogue.

**Comment by Post-Mortem** [comment]
Issue creator has not replied in 3 weeks. Closing issue.
