### ISSUE TITLE
Dreamcast games parsing issue

### ISSUE THREAD

**Issue by Slashic** [TapiocaFox/Daijishou#528]
After downloading the Dreamcast platform and adding some games in a directory on the SD card some games are ignored or merged with other games when parsing the folder with default settings, maybe this affects other systems as well, i haven't checked yet.

**System:** retroid pocket 2+

**Folder layout:**
Game1/game1.gdi
Game1/track01.bin
Game1/track02.raw
Game1/track03.bin

Game2/game2.gdi
Game2/track01.bin
Game2/track02.raw
Game2/track03.bin

Game3/game3.gdi
Game3/track01.bin
Game3/track02.raw
Game3/track03.bin

Only Game1 and 2 appears for instance and if i isolate Game3 in its own folder it's correctly parsed.

I tried renaming them as simple as possible (no space, special chars etc...) but doesn't change the outcome.

**Comment by Jetup13** [comment]
This issue has been posted before so I'm closing this one. Read my explanation [here](https://github.com/TapiocaFox/Daijishou/issues/332#issuecomment-1482008937) on why this happens and how to avoid it. TLDR, they are not uniquely named which causes the gdi files to have the same file hash. 

Hope this helps

**Comment by Slashic** [comment]
Thanks, checked if it wasn't there before but missed it somehow sorry about that, i'll have a look a the workaround.
