### ISSUE TITLE
Your project is incredible!  Make a version for Windows 10!

### ISSUE THREAD

**Issue by carlosgamer23** [TapiocaFox/Daijishou#531]

**Comment by cannnAvar** [comment]
I don't think there will be pc version. Becasue all design for handheald console and mobile phones. For pc there is more options.

**Comment by TapiocaFox** [comment]
Thanks for your love. But it is not possible because the architecture and the underlying technology is very different.

**Comment by carlosgamer23** [comment]
> Thanks for your love. But it is not possible because the architecture and the underlying technology is very different.

I was referring to creating a version for him, not an adaptation, but either way I understand, thank you!
