### ISSUE TITLE
Kiosk mode not working

### ISSUE THREAD

**Issue by gmercado101** [TapiocaFox/Daijishou#533]
I installed from scratch the latest version from playstore.
I toggle on kiosk mode and nothing changes. Version 1.4.66

**Comment by Post-Mortem** [comment]
> I installed from scratch the latest version from playstore. I toggle on kiosk mode and nothing changes. Version 1.4.66

Does the pencil icon on the platforms not disappear when you turn on kiosk mode?

**Comment by gmercado101** [comment]
Yea it dissappears, but path icon is still there. I guess it works,
(partially?) Or is that the intended behaviour. Thanks

**Comment by Post-Mortem** [comment]
That's the intended behavior. You can still add paths and sync in kiosk mode.

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/423
