### ISSUE TITLE
Language and Dropdown menus (Android)

### ISSUE THREAD

**Issue by sxarthur** [TapiocaFox/Daijishou#546]
Hello!
On Android I'm unable to find any way to change the system language... what do i do?

and on dropdown selection menus (like the emulation selection) it starts to type instead of selecting from the dropdown list

**Comment by Post-Mortem** [comment]
1. Android System Language: This process will be different depending on the device. Here's a basic tutorial: https://support.google.com/accounts/answer/32047?hl=en&co=GENIE.Platform%3DAndroid
2. I just tested this and it works fine. Make sure to press the little arrow at the right.
