### ISSUE TITLE
Erotic Games Still Show Up Even With NSFW Content Disabled

### ISSUE THREAD

**Issue by SkeppyTheOne** [TapiocaFox/Daijishou#547]
For Some Reason, Deactivating NSFW Content Dosen't Hide Games With The Erotic Genre 
Might Wanna Fix That!

**Comment by Jetup13** [comment]
The `use_nsfw` flag is only meant to display wallpaper packs marked as NSFW. Never for disabling mature games. The feature was added due to a complaint on Google Play iirc.

You can manually [hide games](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#hiding-games) if you want

**Comment by SkeppyTheOne** [comment]
Oh, Kool

**Comment by SkeppyTheOne** [comment]
That Would Be A Cool Feature Tho
