### ISSUE TITLE
Not showing all installed apps

### ISSUE THREAD

**Issue by MightyX3N** [TapiocaFox/Daijishou#548]
I cant see alot of the apps i have installed under the apps section

**Comment by Jetup13** [comment]
Did you select toggle between only games and apps on the top right?

> Daijishou > Apps tab > Only Games/All Apps

**Comment by MightyX3N** [comment]
Yes i tried on both, it is only newly installed apps that is not showing i think

and also im using the apk on the nvidia shield, so maybe something there is doing something

**Comment by Jetup13** [comment]
Hmm, I'm not sure what could be the issue. Can't reproduce it on my devices. 

Maybe @TapiocaFox can look at this when they have the time
