### ISSUE TITLE
Resume saved state on exit not working on Duckstation 

### ISSUE THREAD

**Issue by ZapperDJ** [TapiocaFox/Daijishou#549]
On the legacy version on Duckstation I could automatically load, as soon as the game started, the state that gets saved the last time I exited the game if I changed the value of resumeState to 1 on the am start arguments, like this:

com.github.stenzek.duckstation/.EmulationActivity
-e bootPath {file.path} 
  --ez resumeState 1 
--activity-clear-task --activity-clear-top 

First of all, I never understood why the value was set to 0 as a default. But what makes me open this issue is that this no longer works with Duckstation ever since it started using scoped storage. I gave both Daijisho and Duckstation access to the ROMs folder, and it seems like the state gets saved when the game is launched via Daijisho, because if I open the game directly through Duckstation I get a prompt to load the state that got saved when I exited the game after starting it through Daijisho

Can this be fixed?

**Comment by Jetup13** [comment]
If you updated Duckstation, the resumeState command no longer works when launched externally (from an ADB session or frontend). I believe it was either quietly removed when Duckstation updated to align with Google's scoped storage rules or was changed (which we can't check as the Android version is closed source the last I checked)

Sten did leave up the Legacy Build downloadable [here](https://www.duckstation.org/android/)

**Comment by Jetup13** [comment]
Closing issue as this is more of a Duckstation question as it involves what Duckstation allows when loaded from a command
