### ISSUE TITLE
Add N-Gage Player

### ISSUE THREAD

**Issue by andiweli** [TapiocaFox/Daijishou#550]
There is EKA2L1 available for Android. A Nokia N-Gage Emulator. It works on the RG405M but I wonder if it is possible to add it's own player and platform for it?

**Comment by Jetup13** [comment]
EKA2L1 doesn't support loading roms from a front-end/adb session the last I checked.

Unless something has changed it can't be added

**Comment by andiweli** [comment]
Oh what a pity… Am 26.10.2023 um 18:58 schrieb Matt Gonzales ***@***.***>:﻿
EKA2L1 doesn't support loading roms from a front-end/adb session the last I checked.
Unless something has changed it can't be added

**Comment by andiweli** [comment]
the developer made it possible by creating json launching files. so launching from dainishou is possible now.
