### ISSUE TITLE
Incompatible with Android TV 12 because of missing file browser

### ISSUE THREAD

**Issue by radry** [TapiocaFox/Daijishou#556]
Version 1.4.67 

The app can be installed via the apk and runs but is estentially unusable:
It is impossible to add "Paths" to each emulator because Android TV lacks the internal file browser, thus it always produces the error "You don't have an app that can do that" when clicking on "Paths". Installing a 3rd party file manager ( I tried MiXplorer which works fin on its own but isn't called by Daijishou) doesn't solve the issue.

Other Android apps that require file access, like retroarch work fine, so it should be possible to fix this issue. Maybe give an option to manually enter a path instead of calling the default android file browser intent.

**Comment by cannnAvar** [comment]
try diffrance exproler. There must be app suport selecting file

**Comment by radry** [comment]
@cannnAvar The problem is with Daijishou and how it handles file exploring. It aparently calls the default android file explorer, which doesn't exist on Android TV. It must be changed in the code to call an app selector or something. Other apps can do it too, they ask which app to use to browser files. I'm not an expert in Android coding.

**Comment by cannnAvar** [comment]
Write

**Comment by GustavoGomez092** [comment]
Refer to #72

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/72
