### ISSUE TITLE
PPSSPP activity still fails to launch if games are in chd format.

### ISSUE THREAD

**Issue by Angstdiscord** [TapiocaFox/Daijishou#561]
Daijishou was unable to launch PSP games after the emulator was updated. This was resolved here
https://github.com/TapiocaFox/Daijishou/issues/430

However this issue still exists if the users games are in chd format.  PPSSPP can load them if using the standalone emulator, but daijisho cannot.

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/179
