### ISSUE TITLE
 YabaSanshiro 2 Pro - Unable to find explicit activity class

### ISSUE THREAD

**Issue by LeeHooker83** [TapiocaFox/Daijishou#562]
Hi

Don't know if its an user error or not but on my Retroid Pocket 3+ with Android 11 there wasn't that error. Used the same setup now on my Odin 2 Pro and i'm not able to start Yabasanshiro 2 Pro, i always see the error message above.

When i directly start Yabasanshirp 2 Pro App all the Games run with no issue.

Is there a setup error on my side or is the emulator itself the issue? Seems that also Android 13 could have a negative impacz cause 11 works good.

Thanks!

best
Chris

**Comment by EgoBizarro** [comment]
I'm surprised it worked on your RP3+, you sure it has Android 11?

I can also only load games from inside the app, not through Daijisho. I think the emu dev doesn't like frontends or something...

**Comment by LeeHooker83** [comment]
> I'm surprised it worked on your RP3+, you sure it has Android 11?
> 
> I can also only load games from inside the app, not through Daijisho. I think the emu dev doesn't like frontends or something...

Pretty sure it worked but i will check again to be sure.

So its more an Emulator issue than Daijisho itself?

**Comment by EgoBizarro** [comment]
I believe I've read from one other person that it worked for them. Bite I believe his Android version was pre-scoped-storage. Yeah, seems there's nothing that can be done on the frontend-side.

**Comment by LeeHooker83** [comment]
i can def. confirm that on my Retroid Pocket 3+ with Android 11 it woerk without any issues.

**Comment by EgoBizarro** [comment]
Where do you keep your Saturn roms?

**Comment by LeeHooker83** [comment]
> Where do you keep your Saturn roms?

both on sd card. internal will be used for GC, PS2, Switch and stuff like this

**Comment by EgoBizarro** [comment]
But in some custom directory or in yaba sanshiro's directory under Android\Data\...

**Comment by LeeHooker83** [comment]
custom - but on booth devices

**Comment by Howchie** [comment]
Same error for me on this and several other emulators

**Comment by kattj83** [comment]
I've got the same issue, I've switched to using the RA yabasanshiro core, it works with daishijou as expected and you get the upscaling options (some games require using different cores but I put that down to just one of those things with Saturn)

**Comment by Howchie** [comment]
My roms are on the sd card and still cannot launch from daijisho

**Comment by Jetup13** [comment]
Hanging this as this has been brought up a number of times here and to the YabaSanshiro 2 dev. It seems to only happen on devices with A12 and up, which leans towards something they would need to fix.

**Comment by devmiyax** [comment]
This issue causeed by changes Android 13. https://medium.com/androiddevelopers/making-sense-of-intent-filters-in-android-13-8f6656903dde

**Comment by devmiyax** [comment]
this is com.magneticchen.daijishou AmStart param

AmStart args: [-n, org.devmiyax.yabasanshioro2.pro/org.uoyabause.android.Yabause, -a, android.intent.action.VIEW, -e, org.uoyabause.android.FileNameEx, /storage/emulated/0/emulation/roms/saturn/v/Street Fighter Zero 3 (Japan).chd, --activity-clear-task, --activity-clear-top, --activity-no-history]

**Comment by devmiyax** [comment]
YabaSanshiro only support  "android.intent.action.MAIN" not "android.intent.action.VIEW"
https://github.com/devmiyax/yabause/blob/master/yabause/src/android/app/src/main/AndroidManifest.xml#L139

android.intent.action.VIEW is needed in intent-filter

**Comment by devmiyax** [comment]
Now it works!

https://photos.app.goo.gl/PhZdngXQrj5p4KCK9

**Comment by Gamesirvictim** [comment]
> Now it works!
> 
> https://photos.app.goo.gl/PhZdngXQrj5p4KCK9

Great, how did you fix it . I have yabasanshiro 2 pro and ES-DE.

**Comment by devmiyax** [comment]
I am a developer of Yabasanshiro. Now it is available on the Google Play store as version 1.14.5.

**Comment by Gamesirvictim** [comment]
> I am a developer of Yabasanshiro. Now it is available on the Google Play store as version 1.14.5.

Great work. I saw you on discord, you were awesome.

**Comment by Jetup13** [comment]
Updated the am start arguments once again (missed the change from `org.uoyabause.android.FileNameEx` to `org.uoyabause.android.FileNameUri`). Confirmed it now launching properly on Android 12 & 13. Thanks again @devmiyax !

**Comment by Gamesirvictim** [comment]
> Updated the am start arguments once again (missed the change from `org.uoyabause.android.FileNameEx` to `org.uoyabause.android.FileNameUri`). Confirmed it now launching properly on Android 12 & 13. Thanks again @devmiyax !

So is it working for you. I couldn't make it work on ES-DE.

**Comment by Jetup13** [comment]
They'll need to update their am start arguments. Looking through their documentation it will look something like this:

> es_find_fule.xml

```
<emulator name="YABASANSHIRO2-STANDALOLNE">
        <rule type="androidpackage">
            <entry>org.devmiyax.yabasanshioro2.pro/org.uoyabause.android.Yabause</entry>
        </rule>
</emulator>
```

> es_systems.xml

```
    <system>
        <name>saturn</name>
        <fullname>Sega Saturn</fullname>
        <path>%ROMPATH%/saturn</path>
        <extension>.bin .BIN .ccd .CCD .chd .CHD .cue .CUE .iso .ISO .m3u .M3U .mds .MDS .toc .TOC .7z .7Z .zip .ZIP</extension>
        <command label="Beetle Saturn">%EMULATOR_RETROARCH% %EXTRA_CONFIGFILE%=/storage/emulated/0/Android/data/%ANDROIDPACKAGE%/files/retroarch.cfg %EXTRA_LIBRETRO%=mednafen_saturn_libretro_android.so %EXTRA_ROM%=%ROM%</command>
        <command label="YabaSanshiro">%EMULATOR_RETROARCH% %EXTRA_CONFIGFILE%=/storage/emulated/0/Android/data/%ANDROIDPACKAGE%/files/retroarch.cfg %EXTRA_LIBRETRO%=yabasanshiro_libretro_android.so %EXTRA_ROM%=%ROM%</command>
        <command label="Yabause">%EMULATOR_RETROARCH% %EXTRA_CONFIGFILE%=/storage/emulated/0/Android/data/%ANDROIDPACKAGE%/files/retroarch.cfg %EXTRA_LIBRETRO%=yabause_libretro_android.so %EXTRA_ROM%=%ROM%</command>
        <command label="YabaSanshiro 2 Pro (Standalone)">%EMULATOR_YABASANSHIRO2-STANDALOLNE% %ACTIVITY_CLEAR_TASK% %ACTIVITY_CLEAR_TOP% %ACTION%=android.intent.action.MAIN %EXTRA_org.uoyabause.android.FileNameUri%=%ROMSAF%</command>
        <platform>saturn</platform>
        <theme>saturn</theme>
    </system>
```
