### ISSUE TITLE
Custom cover art is being forgotten

### ISSUE THREAD

**Issue by SegAgeS** [TapiocaFox/Daijishou#567]
After setting up android as a platform and changing the cover art for each game, when going back into the android platform at a later date some of the cover art has reverted back to the original logos.

I've tried changing settings to not scrape preview media when adding games to the android platform but even then when I add a game sometimes all the art is gone, sometimes only half

**Comment by Jetup13** [comment]
It's how the Android platform is set up unfortunately. It searches apps as if everything new. Hence one of the reasons why it has "depreciated" in the title.
