### ISSUE TITLE
how can i  backup daijishou data

### ISSUE THREAD

**Issue by versrx** [TapiocaFox/Daijishou#572]
android 13. I cant find app folder.so when i change my phone,how can i transfer app's data?or install again,bulid database again?

**Comment by cannnAvar** [comment]
![Screenshot_2023-12-05-11-33-17-143-edit_com.magneticchen.daijishou.jpg](https://github.com/TapiocaFox/Daijishou/assets/72388136/57406590-2477-4162-9563-c389fe8109c2)

You can backup via google drive
