### ISSUE TITLE
Can only scrape box art for non-arcades

### ISSUE THREAD

**Issue by TimeWarpGamer** [TapiocaFox/Daijishou#580]
This worked fine about a week ago, but over the last three days no luck.  Scraping box art always works fine across non-arcade platforms, but title and screenshot never also scrape.  I've tried connecting via WiFi, cellular, and even VPN, same result.  It stopped working at the same time on both my Retroid (Android 11) and my Odin 2 (Android 13), so pretty sure it's an issue bigger than one device/installation.

Love this front-end so much, but this issue is driving me crazy.  When I resynch to try and scrape missing titles and screenshots, it flies through the games like it's not truly pulling any new images.

Interestingly, arcade stuff like fbneo and name and Naomi still scrape correctly without issue.

**Comment by Jetup13** [comment]
It could be a few reasons:

1. Libretro Thumbnails server is currently throwing a SSL certificate error. (This is currently happening right now)
2. It can't find the image as there are none

You can try enabling Aggressive Scraping

> Daijishou > Settings > Library > enable Aggressive Scraping

Import scraped media from [SkraperUI](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#import-scraped-media)

Also check the logger and see if it says anything interesting

> Daijishou > Settings  > Logger

**Comment by TimeWarpGamer** [comment]
Wow, thanks so much for the quick reply.  I really appreciate it.  Must be
#2, because it’s a 100% failure rate and screenshots and images that used
to scrape no longer do

**Comment by TimeWarpGamer** [comment]
Ugh, sorry, I meant #1, not #2

**Comment by peachpieproductions** [comment]
This is happening to me too on the retroid flip, I am only getting box art and no title screens or gameplay images

**Comment by sadamburnley** [comment]
Would be amazing if developer could add add skraper functionality like adding player etc.

**Comment by Jetup13** [comment]
Closing as this is technically a Libretro issue (that being the websites ssl certificate has expired).
