### ISSUE TITLE
Daijisho crashing everytime I show details after 1 sec

### ISSUE THREAD

**Issue by Clads92** [TapiocaFox/Daijishou#581]
Hi,

On my Odin 2, last version of Daijishō, new user (enjoy).
Everytime i want to show detail of a game (no matter on what platform) the app crash. I can brievely see the page like under a second.
I've clear caache/data of the playstore, issue remain.

Thank you !

I can post video, or log if it help

**Comment by Clads92** [comment]
After a reboot few minutes in idle, i've retried and it's now OK, i think the scrapping wasn't finished

**Comment by Clads92** [comment]
After few try it seems random. when i restart my odin 2, the crash when i open details came back again

**Comment by Clads92** [comment]
Please find below a video ↓

https://github.com/TapiocaFox/Daijishou/assets/16538756/f353ccaa-ea72-412e-891b-4a971806b491

**Comment by kattj83** [comment]
I have the same issue, happens across platforms and a reboot/waiting has not resolved for me
