### ISSUE TITLE
quit retroarch hotkey bug

### ISSUE THREAD

**Issue by Tunaa** [TapiocaFox/Daijishou#583]
When I quit retroarch in-game with the hotkey it goes straight to the smartphone homescreen and not back to daijisho. What can I do about that?

**Comment by ghiki** [comment]
Are u sure that the phone itself is not closing Daijisho in the background? Im trying on my Retroid pocket 3+ (with select+down as key combo to close retroarch) and it works perfectly. I also tried in my Poco X3Pro (closing via back gesture), ad also goes to Daijisho menu

**Comment by Tunaa** [comment]
Daijisho and Retroarch are still open in the background. Sometimes it goes back to Daijisho but most of the time it goes back to the smartphone home screen.

**Comment by djusHa** [comment]
Why not to set Daijisho as your default Launcher? Should fix the Problem.

**Comment by Post-Mortem** [comment]
Use daijisho as default launcher.
