### ISSUE TITLE
Unable to load games from mounted drive

### ISSUE THREAD

**Issue by seanstardev** [TapiocaFox/Daijishou#587]
An interesting one, this :)

After much trial and error, I've successfully set my NAS drive to appear as an alias local drive. I used Remount and RSAF to achieve this. 

I can load the games list from this drive just fine in Daijisho, and can scrape media etc.

However - when I come to load the game - a message appears stating that the file is no longer present.

What's strange is that I can load games from that virtual drive in Yuzu, Drastic, Dolphin, Aether SX2 and others, without any issues at all.

... so my hunch is that this frontend is simply confused when asked to load games from anything other than internal storage or sd card?

I notice that when I add a games path it appears as something like:

"tree/{virtual drive name}/path/to/games"

... which seems a bit funky to me.

Any help on this is hugely appreciated, as amongst other things, I'd love to put a tutorial together on how to load games from NAS through this wonderful frontend.

Many thanks :)

**Comment by seanstardev** [comment]
Update: looks like others have encountered this:

https://github.com/TapiocaFox/Daijishou/issues/512

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/512
