### ISSUE TITLE
Won't let change emulator 

### ISSUE THREAD

**Issue by Irish221714** [TapiocaFox/Daijishou#589]
So when press and hold to open up to be able to switch emulator or to see detail. It kicks out of program. I uninstalled and reinstalled same issue.

**Comment by Irish221714** [comment]
Still same

**Comment by Post-Mortem** [comment]
> Still same

Try clearing google play cache.

**Comment by Jetup13** [comment]
https://github.com/TapiocaFox/Daijishou/issues/581

Clear Google Play Services cache
