### ISSUE TITLE
Daijiho  demanding retroarch plus but it can't be installed on my phone

### ISSUE THREAD

**Issue by nnbveh** [TapiocaFox/Daijishou#591]
I have two samsung phones, on the newer one, s21fe daijisho works fine, but on the older one s10, it opens google pay store and obviously wants me to install retroarch plus, but play store says it can not be installed because it was built for an older version or android...i'm not sure why this is happening, i've installed retroarch on both devices from retroarch website(nightly build), and it's enough for s21fe, but not good for s10....

**Comment by Jetup13** [comment]
RetroArch Plus isn't required or even recommended. Use the builds available in the [buildbot](https://buildbot.libretro.com/stable/1.16.0/android/). Then switch player within the platform page if needed
