### ISSUE TITLE
Daijishou loading infinitely when loading platforms

### ISSUE THREAD

**Issue by Myiiy** [TapiocaFox/Daijishou#593]
Hi, recently me (and a few other users on reddit as I can see) have seen and shown a problem in daijishou where on the "Add new platforms" page it loads infinitely and only for a brief second showing a error "java.net.SocketTimeoutException: Failed to connect to (what I assume to be the github address to here, however the logger isnt showing anything on my end), please fix this devs!

**Comment by Jetup13** [comment]
That means your connection to GitHub failed. Try again later or use another connection.
