### ISSUE TITLE
Add RA "Core Provided" on the aspect ratio section for every system options menu.

### ISSUE THREAD

**Issue by iconoclusterdotexe** [TapiocaFox/Daijishou#595]
I'm using an RG405M with GammaOS, and I've noticed there isn't a "Core Provided" setting on the aspect ratio menu section, but only the classic ones (4:3, 16:9, etc.) and the possibility to add a custom value. 
When I tried to disable it by using an empty custom value, on RA it overrides, obviously, with the custom one.
Is there a possibility to add "Core Provided" value to the aspect ratio section to every system? 
Sorry for my bad english. Keep up the good work!

**Comment by Jetup13** [comment]
I'm not sure what this means or what GammaOS is. Daijishou doesn't touch RetroArch's settings. That would need to be edited through RetroArch itself

**Comment by Jetup13** [comment]
There's no setting within Daijishou to edit RetroArch settings is what I'm saying. RetroArch settings need to be changed within RetroArch itself. Though RetroArch by default is set to core provided.

RetroArch settings can be saved by:

> RetroArch > Main Menu > Configuration File > Save Current Configuration

Or Per Game/Core/Directory:

> Open Game with RetroArch > RetroArch Quick Menu > Overrides > Save Game/Directory/Core Overrides

RetroArch must be properly quit for it to retain saves:

> RetroArch > Quit RetroArch 

Sounds like your talking about something GammaOS  is doing. Which I have no clue what that is.
