### ISSUE TITLE
RAWeb update

### ISSUE THREAD

**Issue by HorrorDreamer** [TapiocaFox/Daijishou#601]
The latest version of Daijisho is not up to the latest version of RAWeb, I think it would be a good idea to give the users a way to update RAWeb manually.

**Comment by Alvabeta1993** [comment]
Maybe this is the problem why retroachievemt widget stop working...

**Comment by Jetup13** [comment]
Duplicate https://github.com/TapiocaFox/Daijishou/issues/590
