### ISSUE TITLE
MAME4droid 2024 not working.

### ISSUE THREAD

**Issue by jaemin136** [TapiocaFox/Daijishou#603]
![Screenshot_20240114-025823_Daijish](https://github.com/TapiocaFox/Daijishou/assets/156536854/f5d60161-b094-43c1-8264-d29f7e6f27a8)
![Screenshot_20240114-030329_Daijish](https://github.com/TapiocaFox/Daijishou/assets/156536854/eb0a12ac-518c-4ea0-87a7-8989e30b6fbc)

I tried adding a player based on another reference, but an error keeps popping up.
Please add this emulator for me.

**Comment by ljhmd0825** [comment]
![Screenshot_20240117_160522_Daijish](https://github.com/TapiocaFox/Daijishou/assets/75230324/889d028e-a6b5-43e6-8e14-4f7f2e8c8e3a)
I am using on my device.

**Comment by jaemin136** [comment]
> ![Screenshot_20240117_160522_다이지시](https://private-user-images.githubusercontent.com/75230324/297289518-889d028e-a6b5-43e6-8e14-4f7f2e8c8e3a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODkxOTAsIm5iZiI6MTcwNTQ4ODg5MCwicGF0aCI6Ii83NTIzMDMyNC8yOTcyODk1MTgtODg5ZDAyOGUtYTZiNS00M2U2LThlMTQtNGY3ZjJlOGM4ZTNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEwNTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNGUxNTI4MGMyZTVmMmRlNzMwNzQxMmU4M2RhY2M0ZDUzMDQ4ZDNkNmMzZmEwYjlkYTY0ODMwNzQyNzZmNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X8MiY4oANl688pXgqn-6tKN3yLYeMao_52NrhdUWKgU) 내 장치를 사용하고 있습니다.



> ![Screenshot_20240117_160522_다이지시](https://private-user-images.githubusercontent.com/75230324/297289518-889d028e-a6b5-43e6-8e14-4f7f2e8c8e3a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODk1MjUsIm5iZiI6MTcwNTQ4OTIyNSwicGF0aCI6Ii83NTIzMDMyNC8yOTcyODk1MTgtODg5ZDAyOGUtYTZiNS00M2U2LThlMTQtNGY3ZjJlOGM4ZTNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDExMDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OWFiNjFjY2I0ZTAxMDNlNzVkNmRlZjU1ZjIyYzAyMDYyZjk3OTE5N2FhNTU1ZWUxOGNhYjNlOWU4ZTNkYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FcJNPjsDNApQHQMAbKMo-J7DOp7Vd_ionYwkeRa3CHE) 내 장치에서 사용하고 있습니다.



> ![Screenshot_20240117_160522_다이지시](https://private-user-images.githubusercontent.com/75230324/297289518-889d028e-a6b5-43e6-8e14-4f7f2e8c8e3a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0ODk1NTAsIm5iZiI6MTcwNTQ4OTI1MCwicGF0aCI6Ii83NTIzMDMyNC8yOTcyODk1MTgtODg5ZDAyOGUtYTZiNS00M2U2LThlMTQtNGY3ZjJlOGM4ZTNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDExMDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYWI0OGEyZGMwZjQxMmUwNjhmNjE3MzE0MzQyNzljODUwMDU5NmJhMDM0YjE0MjgwZGZiMDMzYjg3ODM0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oGgDlPGsQMKDhxbv66M6OXbW1ELoplZ8vVVBzs3Vkyg) 내 장치에서 사용하고 있습니다.

Thank you.
What is the difference between file.path and file.uri? Both seem to work fine when tested.

**Comment by jaemin136** [comment]
What is the difference between file.path and file.uri? Both seem to work fine when tested.
