### ISSUE TITLE
Crash trying to go to details on a game

### ISSUE THREAD

**Issue by montero3006** [TapiocaFox/Daijishou#606]
Hello I'm in love with daijisho, I use it since I have my RG505  from last summer. All works awesome.

The problem start after I update GAMMA OS(CFW for RG505) to 1.5.1 but the problem happens on ODIN2 too. 

The problem is that when I try to go to details in a game the daijisho restarts

https://youtube.com/shorts/2EPVClebRFw?si=opYpM0XTqUgc08_M

Here is a video of the problem.

I tried to clean daijishou data and reinstall it, restart machine etc. Always crash and restart daijisho

Thanks to all Devs for that awesome software, is the best of the best.

**Comment by Jetup13** [comment]
Have you looked search through the issues tab?

https://github.com/TapiocaFox/Daijishou/issues/581

Clear Google Play Services cache to resolve the issue

**Comment by montero3006** [comment]
Lots of thanks for the answer! 

I looked some pages on issues page and not seen that post and searched on Google for solution and not find it ,sorry😔
