### ISSUE TITLE
Compatilibity with new mame4droid. 

### ISSUE THREAD

**Issue by tommylipb00t** [TapiocaFox/Daijishou#611]
well, simply it would be cool for daijishou to be able to play new mame4droid.

**Comment by seleuco** [comment]
-n com.seleuco.mame4d2024/com.seleuco.mame4droid.MAME4droid
  -a android.intent.action.VIEW
  -d {file.uri}
  --activity-clear-task
  --activity-clear-top

**Comment by seleuco** [comment]
I'm happy glad to help 😉

https://play.google.com/store/apps/details?id=com.seleuco.mame4d2024

**Comment by tommylipb00t** [comment]
> -n com.seleuco.mame4d2024/com.seleuco.mame4droid.MAME4droid -a android.intent.action.VIEW -d {file.uri} --activity-clear-task --activity-clear-top

what am I supposed to do with that?

**Comment by tommylipb00t** [comment]
hmm I cannot get it to work, how do I add this to a list?

**Comment by seleuco** [comment]
That's for daijishou maintainers so they can add it.

**Comment by tommylipb00t** [comment]
I see. I managed to add it to mg daijisho though. Works great

**Comment by sunydo** [comment]
Thank you for providing the regular expression. I tried using it, but it doesn't seem to work correctly in Dajishou.

**Comment by seleuco** [comment]
Could you elaborate a little more? Its working nice for me.

**Comment by sunydo** [comment]
![49F57823CD5D0432EFCCAF7447C5688B](https://github.com/TapiocaFox/Daijishou/assets/63689398/74dd0d67-26b6-4970-b096-97f1cea7
![BA1296A89DC8F8CCA611E24C2E25B1F9](https://github.com/TapiocaFox/Daijishou/assets/63689398/1729a318-6e16-433f-a322-09d9e2e42162)
2f6e)

**Comment by sunydo** [comment]
If I directly launch the emulator, games can be played normally. However, if I enter through "daijishou," it prompts an error message and then exits.

**Comment by sunydo** [comment]
Another discovery has been made! Other games can be played normally, except for the MONONCOL game, which cannot be accessed.

**Comment by Jetup13** [comment]
Added https://github.com/TapiocaFox/Daijishou/commit/a87e235d550dc152bfaec5d2babd73fd5c1fabca
