### ISSUE TITLE
Daijisho + DuckStation Auto save/load

### ISSUE THREAD

**Issue by kolbasky** [TapiocaFox/Daijishou#612]
Hello,
I have Daijisho `1.4.67` and Duckstation `0.1-6291` (i've tried `0.1-6232` also). And I can't get autosave/load feature working when launching from Daijisho. If I launch games from Duckstation itself - everything works fine, so the feature IS working. There should be some kind of problem with the way I call the app from Daijisho.

At the moment i have following startup arguments:
```
-n com.github.stenzek.duckstation/.EmulationActivity
 -e bootPath {file.uri}
 --ez resumeState 1
 --activity-clear-task
 --activity-clear-top 
```

My OS is `GammaOS_Lite_v1.5`, not sure whether it can be the cause of the problem.

p.s. just checked Duckstation and Daijisho logs - can't find anything useful.

**Comment by porg** [comment]
Thanks for the explanation! Now I understand why all of my attempts below had failed:

---

I have:
- Daijisho 1.4.78
- DuckStation for Android 0.1-6297-g2eea56344 (dev) Built Oct 1 2024 03:08:52

Wondered how I can get the auto resume feature to work when DuckStation is launched via launcher and exiting back to that launcher.

1) I looked into the Daijishou wiki how [Start Arguments](https://github.com/TapiocaFox/Daijishou/wiki/Start-Arguments) work by looking at:

- a) [Start Arguments Cheat Sheet](https://github.com/TapiocaFox/Daijishou/wiki/Start-Arguments-Cheat-Sheet) 

- b) How in general one programmatically invokes Android apps and their activities via Android Debug Bridge ([adb](https://developer.android.com/tools/adb)) with the Activity Manager ([am](https://developer.android.com/tools/adb#am)).

2) But I found no proper documentation about Duckstation's environment variables, particular for Android (no source code). I even downloaded the [.apk](https://downloads.duckstation.org/android/), decompressed it (its a ZIP archive) and then decoded the binary XML file with [axmldec](https://github.com/ytsutano/axmldec), inspected it, also ran a full text search "resume" in the whole decompressed archive, found nothing anywhere.

  - The closest resource I found was the wiki on [Command Line Arguments for the Windows .exe](https://github.com/stenzek/duckstation/wiki/Command-Line-Arguments) which listed the shorter argument `-resume`.

  - I had tried various permutations of:

        [-e|--ez|-esn] [resumeState|resumestate|resume] [1|on|true|yes]

  - to no avail.

Lucky that I found this info here eventually.
