### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by sagotch** [TapiocaFox/Daijishou#615]
Hi. From the README file, you can read:

> Nonetheless, I do have some prerequisites for open-sourcing it.

Could you explain what it means?

You stated that you do not have time to work on it anymore, and I fear that Daijishou will soon be another closed-source abandoned software software stuck in its last known state.

**Comment by sagotch** [comment]
Sorry for the noise. I didn't see the existing issue about it.

**Comment by sagotch** [comment]
Actually, that's another thing and do not answer my question.

**Comment by Post-Mortem** [comment]
Please use our official discord to discuss this with the developer:

https://discord.com/invite/nJbxdT3QQE

**Comment by GeorgeGedox** [comment]
> Please use our official discord to discuss this with the developer:
> 
> https://discord.com/invite/nJbxdT3QQE

These things should be discussed publicly, not in a private and very volatile environment like discord. This just proves that there is no intention of open-sourcing this project

**Comment by MessiasLima** [comment]
Open-sourcing it would prevent it from dying. I really hope the main developer think it better
