### ISSUE TITLE
[Feature Request] Disable Widgets tab entirely

### ISSUE THREAD

**Issue by MANGOM1LK** [TapiocaFox/Daijishou#617]
Currently, the toggle for the Widgets tab just turns it into the Genres tab when disabled. The Apps tab toggle works (mostly) as it should, so I'm not sure why this toggle doesn't work in the same way. I don't have much use for either a Widgets tab or a Genres tab so this is pretty redundant for me. Would it be possible to do the following?:

1. Make the Widgets toggle work the same way as the Apps toggle, where it removes the tab completely
2. Add a Genres toggle which does this for the Genres tab

**Comment by TapiocaFox** [comment]
Disable widgets page will automatically turn it to genres tab (it is now called categories).
