### ISSUE TITLE
Apps toggle can result in a blank Settings menu

### ISSUE THREAD

**Issue by MANGOM1LK** [TapiocaFox/Daijishou#618]
The toggle for the Apps page moves the Settings page one tab to the left when it's disabled. It appears as if this is its own seperate implementation of the Settings page, because this sometimes results in the page being blank aside for the section title (Navigation, since that's where this toggle is). Pushing B at this point (or the Android back button) just moves you back to the Platforms tab, so there's no way to get the Settings menu working again short of restarting the app - and when this is the default home screen app, that can only be done in the Android system settings. This behavior is not consistent, though - sometimes it correctly shows the Navigation section when you toggle this option on, so I'm not exactly sure what's causing the problem. Will report more as I find it

**Comment by Jetup13** [comment]
https://github.com/TapiocaFox/Daijishou/issues/592
