### ISSUE TITLE
Feature Request: Add screenscraper.fr support

### ISSUE THREAD

**Issue by agaskins** [TapiocaFox/Daijishou#623]
Screenscraper is by far the most complete sraping source available. Currently Daijisho does okay with scraping but it misses way too much by default, and gets too much wrong when enabling aggressive scraping. Screenscraper supports threads and so many things (front/back/screenshot/titlescreen/3dbox/video/etc.). Even if you just scrape the front box cover with it, I think it would atleast give more complete scrape results. Bonus points if Daijisho could display the small video previews that screenscraper supoorts :P

**Comment by Raleighite** [comment]
Id love to see support for Screen Scrapper.

**Comment by Post-Mortem** [comment]
#194
