### ISSUE TITLE
[Feature Request] Separate Apps and Games Tabs

### ISSUE THREAD

**Issue by nascentt** [TapiocaFox/Daijishou#628]
I know you can toggle from All Apps to Games, but an Apps tab (with no games) and a Games tab separated out would be so much more useful.

**Comment by feress737** [comment]
You can add a Android Platform Page.
Download this file and remove the "deprecated" at the end.
https://github.com/TapiocaFox/Daijishou/blob/main/platforms/Android.json.deprecated

Then import this platform over the Daijishou settings.
This platform will show all as game marked Android apps.

**Comment by nascentt** [comment]
> You can add a Android Platform Page. Download this file and remove the "deprecated" at the end. https://github.com/TapiocaFox/Daijishou/blob/main/platforms/Android.json.deprecated
> 
> Then import this platform over the Daijishou settings. This platform will show all as game marked Android apps.


thanks, this is actually great! I'm surprised it's deprecated.
