### ISSUE TITLE
Possible issue: detection of multiple ROMs with the same filename

### ISSUE THREAD

**Issue by npaladin2000** [TapiocaFox/Daijishou#630]
Some explanation probably needed here. I have a number of games with MSU1 soundtracks. And several optional soundtracks. I set them up in seperate subfolders but the same ROM name, so I can switch back and forth between soundtracks while keeping the same save games and states. it appears that Daijisho is only presenting the first detected ROM and ignoring the others though, whether "grouping similar named ROMs" is enabled or disabled. Besides, they're named exactly the same, is it possible a routine somewhere is picking them up as duplicates and ignoring them that way?

**Comment by Jetup13** [comment]
Daijishou adds items to a platform by checking the md5 hash, not the name or path. So if two items have the same md5 hash it ignores the other.

**Comment by npaladin2000** [comment]
Ok, that's obviously a problem for what I'm doing then. That'll impact anything that has the same MSU1 patch but multiple different soundtracks. Not sure what there is to do about it though, if anything. If it's got a different name it may still have the same hash...

**Comment by Jetup13** [comment]
The naming of a file doesn't change the file hash. The contents of the file does.

**Comment by npaladin2000** [comment]
So will this be changed?

**Comment by Jetup13** [comment]
No clue. What you can do is use RetroArch's [soft patching feature](https://github.com/Jetup13/Retroid-Pocket-3-Plus-Wiki/wiki/RetroArch#softpatching).

Example -

Set 1:
EarthBound (USA).sfc (not patched)
EarthBound (USA).ips (the MSU patch)
EarthBound (USA).msu
EarthBound (USA)-*.pcm

Set 2:

EarthBound (USA) (Patched).sfc (this file is already patched)
EarthBound (USA) (Patched).msu
EarthBound (USA) (Patched)-*.pcm

This should produce two different md5 hashes thus allow two different entries. Soft Patching feature isn't supported everywhere so keep this in mind.
