### ISSUE TITLE
[SYSTEM FILES] - Question About System Files: I've tried several ways but I haven't found where the Daijisho files are located on ADNROID.

### ISSUE THREAD

**Issue by claudneysessa** [TapiocaFox/Daijishou#632]
Hello, I would like to customize my lists and adjust the games by category, I managed to do this manually but it is a very hard work using the launcher, where I can find the files within the Android to edit them in a more practical way on my computer and return them?

**Comment by claudneysessa** [comment]
I did it like this using the launcher

![image](https://github.com/TapiocaFox/Daijishou/assets/12506432/25807f4e-86c1-499c-baa7-fb24f772c54a)

However, I want to add cross-platform games here related to racing games by putting the console prefix before the name like I did with this specific game

![image](https://github.com/TapiocaFox/Daijishou/assets/12506432/8a3754dd-1f4e-45f5-b52f-f4b22d50d6ce)

I saw that it is possible to do it because on the original platform it remains correct without the changes, but doing it through the launcher is very time-consuming and boring...

Can I get the file pulled into Windows to edit and return it?

**Comment by david79111** [comment]
This is a help me question which belongs to the discord channel as stated in the rules for creating new issues. Please close this issue and go to discord with your question.
