### ISSUE TITLE
MD.emu not working

### ISSUE THREAD

**Issue by ialtag-bheag** [TapiocaFox/Daijishou#633]
I'm using a Retroid Pocket 2S,.

I have setup Dajisho for Sega Genesis with MD.emu. But if I try launching a game, it just briefly flashes up a black screen. Sometimes it briefly shows an error message. Though if I try launching the game a few times, sometimes it works.
Have tried the option for kill package processes, that doesn't seem to make any difference.

Works fine if I just use the emulator separately, and load the games. I am using several other .emu emulators with Daijisho, they are working fine. Is there something different about how MD.emu works?

**Comment by Jetup13** [comment]
Loads just fine for me (Retroid Pocket 4 Pro, using No Intro romset)
Not sure why your having issues.. What's the file type or romset your using? Have your tried using another frontend to see if your encountering the same issue?

https://github.com/TapiocaFox/Daijishou/assets/62556437/390269c5-4158-4918-94b9-ed85a6550d91
