### ISSUE TITLE
Add support for Suyu Nintendo Switch emulator (player)

### ISSUE THREAD

**Issue by snoopymail** [TapiocaFox/Daijishou#634]
As described in title

**Comment by Jetup13** [comment]
Added to [9a2e15f](https://github.com/TapiocaFox/Daijishou/commit/9a2e15f7bbe21f3faec27a9e5eadb95837437411). I didn't get to test it so I'm unsure if it even supports launching from frontends

**Comment by snoopymail** [comment]
Works perfectly!  Many thanks!
