### ISSUE TITLE
On Fire TV, unable to select a path

### ISSUE THREAD

**Issue by brandon-james105** [TapiocaFox/Daijishou#637]
I am using a standard Fire TV and when I download an emulator, then click paths, the file browser will appear, but it will freeze until I press the back button.

**Comment by brandon-james105** [comment]
I found a workaround, which is to have a keyboard and mouse on the TV. I was able to select the file paths I was looking for. This is not a good solution, as you need to set this up, and there are caveats. When I am on the file select screen, the cursor is invisible. You can still click things, but it's a total guess because you can't tell where you are clicking. If a keyboard is connected to the TV, then you can use the "TAB" key to hover the UI element, and the "ENTER" key to select it.

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/72

**Comment by bitrot-alpha** [comment]
For anyone finding this via a search engine, there is a way to make this work without connecting a physical mouse and keyboard, but the same caveats apply (invisible mouse cursor, etc).

You need to enable ADB debugging access on your Fire TV device, and something to run an ADB shell while in front of the TV like a laptop or Android phone. I use Termux, but there's also dedicated ADB apps such as [Remote ADB Shell](https://play.google.com/store/apps/details?id=com.cgutman.androidremotedebugger). For mouse cursor you need [ADB Mouse](https://play.google.com/store/apps/details?id=svarzee.android.apps.adb_mouse). 

Get your Fire TV device's IP from **Settings -> My Fire TV -> About -> Network.** If you're using Termux, do a `pkg update` and `pkg install android-tools` to install ADB, and then run `adb connect [your fire tv IP no brackets]`. After running `adb connect` you should see a prompt on your Fire TV device. This prompt should also show immediately after you put your IP into Remote ADB Shell and hit 'Connect,' or put your IP into ADB Mouse. You will have to accept the ADB prompt on your Fire TV for each app you use.

To send a virtual tab key for navigating the Android Files app, run `adb shell` if using Termux, and then run `input keyevent 61`. Re-run the `input keyevent 61` command as many times as necessary to move the button selection to what you want. On Termux a nice shortcut is to hit the up arrow button on the utility bar above the keyboard. If you can't see your files, you may have to go to the three dots menu on the top-right in the file manager and select "Enable internal storage" if you're using a Fire Stick HD (codename sheldon) or similar. I got this command from https://www.aftvnews.com/how-to-use-the-system-picker-files-app-in-fire-os-8-on-the-2nd-gen-fire-tv-stick-4k-4k-max-to-grant-access-to-external-usb-storage-drive-folders/

For setting up emulators, it may be easier to manually type in the file paths with the Fire TV phone app and not use the janky file picker UI. This worked for me on Robert Broglia's Snes9xEX+ and MD.emu. The internal storage path is `/sdcard` or `/storage/emulated/0`. Example paths: `/sdcard/saves`, `/sdcard/roms/snes`. I had to grant the emulators storage access in order for my settings to stick. This prompt will show up the first time the app opens the file picker UI. You don't actually have to choose a path (I don't think, I had to try multiple times to get anything to 'stick').
