### ISSUE TITLE
Feature request - Abilitiy to use scraper

### ISSUE THREAD

**Issue by tommylipb00t** [TapiocaFox/Daijishou#638]
It would be ccol to have it

**Comment by Jetup13** [comment]
Not sure what you mean. Do you mean SkraperUI? If so you can use items generated by it by [manually importing](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#import-scraped-media) them

**Comment by BlueApolo** [comment]
I believe he suggested that the user have some different options of which scrapers to use. Launchbox, GamesDB etc. 
It would be nice.

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/501
