### ISSUE TITLE
Error with 3DS opening roms .3ds

### ISSUE THREAD

**Issue by SerraLanao** [TapiocaFox/Daijishou#642]
I am using Citra (org.citra.emu) in Daijishou and I get the error "Invalid ROM Format". 

![Uploading Screenshot_20240404-201352.png…](Error showing) 

The ROM opens correctly in Citra, and has the .3ds format and not .CIA,  but not if I'm able to ope it from Daijishou.

Is there a Bug or a fix for that? 

Thanks.

**Comment by Jetup13** [comment]
.3ds format launches just fine when I tested it. Make sure your roms are not encrypted
