### ISSUE TITLE
Can't install platform wallpaper pack

### ISSUE THREAD

**Issue by AdityaMH** [TapiocaFox/Daijishou#643]
Can't install platform wallpaper pack from daijishou.github.io/gallery/

most of them hidden in setting > appearance > download platform wallpaper pack.

i only can download few wallpaper pack instead all on website list.

**Comment by Jetup13** [comment]
A few of the packs require NSFW mode to be enabled

> Daijishou > Settings > About Daijishou > Tap logo 7x to enable NSFW mode
