### ISSUE TITLE
Add lime3ds

### ISSUE THREAD

**Issue by MrArdillo** [TapiocaFox/Daijishou#646]
Add Lime3DS as an emulator option for 3ds

**Comment by Jetup13** [comment]
[7c79919](https://github.com/TapiocaFox/Daijishou/commit/7c799192ba3630c026aee0a306fa18286ea3078f)

Please [update](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#updating-platforms) the 3DS platform
