### ISSUE TITLE
Suggestion - Update G&W platform 

### ISSUE THREAD

**Issue by hartleyshc** [TapiocaFox/Daijishou#649]
Suggestion to update the Game & Watch platform to support the Mame Retroarch core for those roms.

**Comment by Jetup13** [comment]
I'll give this a check when I can

**Comment by Jetup13** [comment]
I could not get them to work on the Android build of RetroArch's (1.18.0) MAME Current core (02.64 170929e0). Can you provide a tutorial? 

Also you can add the MAME players yourself by manually adding it to the json file or downloading the mame platform > add mame players to the gw platform.

**Comment by hartleyshc** [comment]
Found the issue. They are actually using the latest MESS core (which labels itself in retroarch as the mame core).

Here is the line from the platforms file for ES-DE

`<command label="Multi (MESS)">%EMULATOR_RETROARCH% %EXTRA_CONFIGFILE%=/storage/emulated/0/Android/data/%ANDROIDPACKAGE%/files/retroarch.cfg %EXTRA_LIBRETRO%=mamemess_libretro_android.so %EXTRA_ROM%=%ROM%</command>`

I tested on retroarch and I was able to load the MESS emulator, and then the mame based g&w roms loaded no problem.

**Comment by hartleyshc** [comment]
So I confirmed it works by editing and then sideloading the current Game&watch.json platform file. 
No idea if this is correct, but just tried to match the current naming conventions of things. 
Also not sure if MESS is available on on the 32bit version of Retroarch or not. I know initially it was 64bit only, but that was a year or so ago. 

`    {
      "name": "gw - RetroArch 64 - mess",
      "uniqueId": "gw.ra64.mess",
      "description": "Supported extensions: 7z, chd, cmd, zip.",
      "acceptedFilenameRegex": "^(.*)\\.(?:7z|chd|cmd|zip)$",
      "amStartArguments": "-n com.retroarch.aarch64/com.retroarch.browser.retroactivity.RetroActivityFuture\n  -e ROM {file.path}\n  -e LIBRETRO /data/data/com.retroarch.aarch64/cores/mamemess_libretro_android.so\n  -e CONFIGFILE /storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg\n  -e IME com.android.inputmethod.latin/.LatinIME\n  -e DATADIR /data/data/com.retroarch.aarch64\n  -e APK /data/app/com.retroarch.aarch64-1/base.apk\n  -e SDCARD /storage/emulated/0\n  -e EXTERNAL /storage/emulated/0/Android/data/com.retroarch.aarch64/files\n  --activity-clear-task\n  --activity-clear-top",
      "killPackageProcesses": true,
      "killPackageProcessesWarning": true,
      "extra": ""
    },`

**Comment by Jetup13** [comment]
Sorry for the late reply, I updated the platform [c08b60c](https://github.com/TapiocaFox/Daijishou/commit/c08b60c5d60cb72424b600171cfe2e94b2565eac). It should work in both RA64 and RA (mess is not available on 32bit)
