### ISSUE TITLE
Sudachi in daijishou

### ISSUE THREAD

**Issue by tommylipb00t** [TapiocaFox/Daijishou#650]
Has anyone managed to do that? simple editing and renaming of the package name doesnt work (I replace package name of yuzu player with sudachis' package name, doesnt work - unable to find explicit activity bug.)
thats yuzu player:
-n org.yuzu.yuzu_emu/org.yuzu.yuzu_emu.activities.EmulationActivity
  -a android.nfc.action.TECH_DISCOVERED
  -d {file.uri}
and sudachi:
-n org.sudachi.sudachi_emu.ea/org.sudachi.sudachi_emu.ea.activities.EmulationActivity
  -a android.nfc.action.TECH_DISCOVERED
  -d {file.uri}

any help?

**Comment by Jetup13** [comment]
Forgot to close those as Sudachi was added awhile back
