### ISSUE TITLE
Citra mmj antutu

### ISSUE THREAD

**Issue by stevenwhat68** [TapiocaFox/Daijishou#651]
Please help me make this workkkkkkk i cant play it via app it always force close when i push the play button, im on an Android btw not a console type handheld

**Comment by Jetup13** [comment]
There's a lot of issues with Citra when it comes to launching from a frontend. There's not much Daijishou can do as it's usually a Citra related problem

Try the following:

1. Make sure Daijishou and Citra use the same roms paths
2. Try launching Citra before selecting a game on Daijishou
3. Try a different Citra version
4. Try updating the platform
5. Try updating the am start arguments for the selected Citra player by switching {files.uri} to {files.path} or vice-versa

**Comment by stevenwhat68** [comment]
Ohhh ok , one more question how to use the same rom paths? The first one you said.

**Comment by Jetup13** [comment]
Pretty much every standalone app needs permissions to see and use user selected paths. 

Make sure the path of your roms are the same between Citra and Daijishou. For instance if you selected `roms/3ds/` within Citra, make sure Daijishou has that same folder synced within the 3ds platform.
