### ISSUE TITLE
About vita3k repair plan 

### ISSUE THREAD

**Issue by EagleFlyInSky** [TapiocaFox/Daijishou#652]
#222 
I have responded to the mentioned issues and provided solutions. But an update is nowhere in sight.
I hope SonyPSVita.json can be updated before the App fixes the problem。
`-n org.vita3k.emulator/org.vita3k.emulator.Emulator\n --esa AppStartParameters -r(?<!\\\\),{tags.game_id}`
This code currently starts the psv game correctly.

**Comment by Jetup13** [comment]
Thanks, sorry for the long response. @TapiocaFox is currently away for school/life and it might take them time to respond. In the meantime I've been the one the past few months updating the platforms. 

I've confirmed the start argument as working so I'll update the Vita platform. Thanks and sorry again for the late response.

**Comment by Jetup13** [comment]
Added Vita as a selectable platform to the index. I'll close this and move the discussion to the og topic
