### ISSUE TITLE
suggestion - ability to change fonts

### ISSUE THREAD

**Issue by god-s-perfect-idiot** [TapiocaFox/Daijishou#657]
Would be really cool if it was possible to change the font

**Comment by Post-Mortem** [comment]
i believe you can change the fonts if you change your device's font in system settings.

**Comment by Jetup13** [comment]
Correct, Daijishou will use the devices font.

**Comment by god-s-perfect-idiot** [comment]
Can confirm this doesnt work on Lineage OS

**Comment by Jetup13** [comment]
Hmm, not sure why its not working. It definitely works on my Samsung device when I tried it. Though Android versions very from vendor to vendor so the setting to change device font might be in an area you wouldn't expect it. I don't use Lineage OS so I'm not sure where they have there font options.

> Android Settings > Accessibility > Visibility enhancements > Font size and style  > Font style
![Screenshot_20240620-232509_Settings](https://github.com/TapiocaFox/Daijishou/assets/62556437/e2e857eb-76ec-4152-8155-3a99be7df7b0)


> Default
![Screenshot_20240620-232546_Daijish](https://github.com/TapiocaFox/Daijishou/assets/62556437/9231a135-9113-4439-883d-8185452ac781)

> Cool Jazz
![Screenshot_20240620-232525_Daijish](https://github.com/TapiocaFox/Daijishou/assets/62556437/34eba887-d380-44ae-9cb9-e2fe78466f60)
