### ISSUE TITLE
"Path" button appearing in Kiosk mode

### ISSUE THREAD

**Issue by Joe-Vicentini** [TapiocaFox/Daijishou#661]
I understand that kiosk mode is meant to be the non-configurable/editable interface of Daijishou. Let's say I want my kid to play with my Retroid and I don't want him messing up with my library and my setup. For this to be fully accomplished, "path" button should be hidden in Kiosk mode.

**Comment by Post-Mortem** [comment]
https://github.com/TapiocaFox/Daijishou/issues/423
