### ISSUE TITLE
add emulators manually

### ISSUE THREAD

**Issue by david79111** [TapiocaFox/Daijishou#662]
Please add the option to add emmulators manually until the developer adds them to Daijishou himself.
This is especially useful when the dev is inactive for a while and new emators pop up.

I wanted to add lemuroid, but it's not available.

**Comment by Jetup13** [comment]
Lemuroid doesn't support launching roms from a frontend or adb session. I've been updating the platforms for the past year or some odd months. Make to keep the platforms up-to-date for the latest players by -

Manually updating platforms:

> Daijishou > Download

Or enabling Update platforms automatically:

> Daijishou > Settings > Library > Enable Update platforms automatically

Also you can already add your own players:

> Daijishou > Settings > Library > Add a player

You can also create/edit json files. You can see how they are typically setup by looking at the official platform json files [here](https://github.com/TapiocaFox/Daijishou/tree/main/platforms)

Hope this helps!

**Comment by david79111** [comment]
Thanks.
