### ISSUE TITLE
Yuzu and citra

### ISSUE THREAD

**Issue by Javiert54** [TapiocaFox/Daijishou#666]
The repositories are not updated, so, when I try to download the emulators sugested for 3ds or switch, it takes me to the yuzu/citra playstore, but It is no longer available, so I can not play 3ds or switch.

**Comment by Jetup13** [comment]
Citra and Yuzu have both been [shutdown a few months ago](https://x.com/yuzuemu/status/1764733659444064671). They both have quite a few forks though, try using those instead. As for which is best that's for you to decide.
