### ISSUE TITLE
Launching Mupen64plus GLES3 or Parallel64 Retroarch cores through FE does not launch rumble

### ISSUE THREAD

**Issue by Kevinwensh93** [TapiocaFox/Daijishou#675]
Piggybacking on this issue:

https://github.com/TapiocaFox/Daijishou/issues/181

While setting polling to early solves the issue of the controller being immediately recognized rumble will never work no matter what configuration I put into it. Just like the above issue, there are no problems at all when using Retroarch proper.

I am using ES-DE Frontend.

**Comment by Kevinwensh93** [comment]
I'm dumb and I opened an ES-DE issue for the wrong frontend

**Comment by Jetup13** [comment]
I can still answer since it happen when loaded from frontends. The N64 cores have *many* issues with controls

To fix this particular issue enable Threaded Renderer via RetroArch Quick Menu:

> RetroArch Quick Menu > Core Options >GlideN64 > Threaded Renderer
