### ISSUE TITLE
Radio App

### ISSUE THREAD

**Issue by Aqua-Cloudya** [TapiocaFox/Daijishou#678]
A radio App either the one that came with this device or a lineage one would be nice

**Comment by Jetup13** [comment]
I'm not sure what you mean by came with this device or a lineage one? Daijishou is not a device or firmware. It's just a simple frontend app

There's an apps tab and Android platform. You can simply mark an app as a game to add it to the platform or load an app from the tab

**Comment by Aqua-Cloudya** [comment]
When you first buy the anbernic there was this radio app that came with it pre installed like it was built in but once i used gamma it disappeared

**Comment by Jetup13** [comment]
I'm not sure what Gamma is but it sounds like a question for them. Daijishou is just a frontend.
