### ISSUE TITLE
Flycast Emulator Random Error

### ISSUE THREAD

**Issue by Romulus1976** [TapiocaFox/Daijishou#683]
Standalone Flycast emulator randomly quit working. Some issue has happened with the startup arguments. 

Got an error stating, 

"Unable to find explicit activity {com.flycast.emulator/com.flycast.MainActivity} Have you declared this activity in your Android Manifest.xml"

Is their somewhere where the correct arguments are listed. I noticed the player Json files were updated 2 days ago. Could that be the issue.

**Comment by Jetup13** [comment]
Update your Flycast build. The am start arguments recently changed. 

[Flycast master/dev builds](https://flyinghead.github.io/flycast-builds/)/[Google Play](https://play.google.com/store/apps/details?id=com.flycast.emulator)

**Comment by Romulus1976** [comment]
Thank you

**Comment by Romulus1976** [comment]
Is their any way to roll back and use the previous player arguments. The old version of Flycast performed a lot better on my machine. I'm running this on an arcade 1up and forgot to turn off the auto update platforms feature.

**Comment by Jetup13** [comment]
Create a new player:

> Daijishou > Settings > Library > Add a Player

Enter these details:

> Player name

```
dreamcast - Flycast (Legacy)
```
> Player am start arguments

```
-n com.flycast.emulator/com.reicast.emulator.MainActivity
-a android.intent.action.VIEW
-d {file.path}
```

> Player accepted filename regex

```
^(.*)\\.(?:7z|bin|cdi|chd|cue|elf|gdi|lst|zip)$
```

> Kill package processes before am start 

``
off
``

Save

You can associate the player to a platform if you want:

> Daijishou > Settings > Library > Inspect Platform > Dreamcast > Search additional player to be added dropdown > dreamcast - Flycast (Legacy) > Add to the list > Save

**Comment by Romulus1976** [comment]
Thanks again. I ended up downloading the Json from before the platforms were updated. Your tutorial actually helped with another issue I was having.
