### ISSUE TITLE
Too many clicks!

### ISSUE THREAD

**Issue by sudeep23** [TapiocaFox/Daijishou#686]
I’m new to Daijishou and I love it! But one very small thing is really bothering me and feel like can/should be simplified: extra 2,3 taps for basic stuff like starting game or going back. Few detailed example:

Pin and Play Widget:
- These are supposed to be game that you play often and want to start immediately.
- But when I select a pinned game:
- 1. I see detail page, which seems unnecessary by default for the game you are actively playing.
- 2. Then tap multiple left right to goto “Play” and finally you can start a game! 
- This should simply be Select and start the game. Maybe move details page to hotkey. Or atleast have setting to directly start pinned game.
- I don’t know why but this is driving me crazy! 😂

Platform Grid View Back Button
- When I open a platform in grid-view and press back button, instead of going back to home page, platform title gets selected. I have to press back again to goto home screen. 
- Again 1extra click for no reason. 

Settings Back Button:
- any settings page, one back button takes you to top and need another back button to actually go back.
- I feel this is not necessary as setting pages arent that long.

**Comment by david79111** [comment]
I agree, thanks for opening an issue on this. I was too lazy to do it myself.
This is like the only thing about the frontend that bothers me apart from disabling the back button sound doesnt work for me.

**Comment by TapiocaFox** [comment]
Will be improved in `1.4.70`. `onBackPressed()` skips animation if `recyclerView.scrollState==ViewPager2.SCROLL_STATE_SETTLING` and other constants fullfilled. `Detail view on click` toggle added as well.

**Comment by david79111** [comment]
I'm not sure if you will implement all the points above in future updates. You said that in 1.4.70 something will be improved and 1.4.70 came out but it didnt seem to fix any of the points above.
Just wanted to know if you'll implement them in future updates?

**Comment by sudeep23** [comment]
@TapiocaFox Thanks for fixing this. Like David mentioned, 2 of the mentioned issues are fixed (Settings and widget detail option) but multiple back button from grid view to platform still exists. Are you also planning to address that or are we missing something?

**Comment by david79111** [comment]
I doubt he'll see it. Do you want to open a new issue on the grid view click?
