### ISSUE TITLE
FBN won't add game

### ISSUE THREAD

**Issue by Ecabmad** [TapiocaFox/Daijishou#689]
When i scrape some fbn roms, it won't scrap dariusg.zip or dariusgx.zip. It will only scrape the latter. If i add first the first one, then it won't scrap the second one after. They aren't the same game. I've tried both enabling "show duplicate games" and importing a new xml with all the romset data.

![files_sceenshot_2024-08-25 132518](https://github.com/user-attachments/assets/618102e3-276f-4cab-b366-6e9c972d9b4b)
![Screenshot_20240825-132341_Daijishō](https://github.com/user-attachments/assets/4f1309f7-d25a-45c9-9f1a-0051595be764)

**Comment by Jetup13** [comment]
Daijishou syncs games by md5. It only looks for at the first 4MBs of the file. The first 4MB's of those two files might be similar. 

You can try repacking one of the files, that should give it another file hash

**Comment by Ecabmad** [comment]
It woked, I unzipped and repacked as a *.7z and got recognized, thanks.
