### ISSUE TITLE
Issues & Suggestions

### ISSUE THREAD

**Issue by davehartleyuk** [TapiocaFox/Daijishou#691]
So glad there's updates for this again. By far the best front end I've tried. 

Not sure to what level you're working on this and I'm sure you're aware of this issue:

Vita games don't open in Vita3k. It launches the app but doesn't launch the game, it just returns to game list in Daijisho.

One thing I really like the look of in ES-DE is the Custom Game Collections. Like the favorites you have but can group games together under any header. So I could for example have a Zelda collection that has all Zelda games from all consoles in one place. 

Thanks again for building such a great app/front end!

**Comment by davehartleyuk** [comment]
> There was a small change in the Daijishou update to correct the issue from #222
> 
> Update the PS Vita platform for the latest Vita3k am start argument

I've done this but it still just opens Vita3k but doesn't launch any games. Am I missing something really obvious here?

**Comment by Jetup13** [comment]
Just tested on my end and it works.

Did you update the [PS Vita platform](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#updating-platforms)? If yes, what is your [am start](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#edit-players) for Vita3k?

**Comment by davehartleyuk** [comment]
I did.

{
    "databaseVersion": 8,
    "revisionNumber": 4,
    "platform": {
        "name": "Sony PS Vita",
        "uniqueId": "vita",
        "shortname": "vita",
        "description": null,
        "acceptedFilenameRegex": "^(?!(?:\\._|\\.).*).*$",
        "scraperSourceList": [
            "LIBRETRO:Sony - PlayStation Vita",
            "DSESS:BOX_ART:TAGS(scraperKeyword):https://thegamesdb.net/search.php?name=%7BscraperKeyword%7D&platform_id%5B%5D=39&dsess_selector=img.card-img-top&dsess_attribute=src&dsess_replacer=images%5C%2F.%2A%5C%2Fboxart&dsess_replacer_value=images%2Foriginal%2Fboxart",
            "DSESS:GENRES:TAGS(scraperKeyword):https://thegamesdb.net/search.php?name=%7BscraperKeyword%7D&platform_id%5B%5D=39&dsess_target_site_selector=div.col-6+a&dsess_target_site=.%2A%5C%2Fgame.%2A&dsess_selector=div.col-lg-8+div.card-body&dsess_extractor=.%2A%3Cp%3EGenre%5C%28s%5C%29%3A%28.%2A%29%3C%5C%2Fp%3E",
			"DSESS:BOX_ART:TAGS(scraperKeyword):https://www.mobygames.com/search/quick?q=%7BscraperKeyword%7D&p=105&search=Go&sFilter=1&sG=on&dsess_target_site_selector=div.searchTitle+a&dsess_target_site=%5Ehttps%3A%5C%2F%5C%2Fwww%5C.mobygames%5C.com%5C%2Fgame%5C%2Fmsx%5C%2F.%2A%24&dsess_selector=div%23coreGameCover+img&dsess_attribute=src&dsess_replacer=%5C%2Fs%5C%2F&dsess_replacer_value=%2Fl%2F"
        ],
        "boxArtAspectRatioId": 0,
        "useCustomBoxArtAspectRatio": true,
        "customBoxArtAspectRatio": "256:327",
        "screenAspectRatioId": 0,
        "useCustomScreenAspectRatio": true,
        "customScreenAspectRatio": "5:3",
        "retroAchievementsAlias": null,
        "extra": ""
    },
    "playerList": [
        {
            "name": "vita - vita3k",
            "description": "Supported extensions: dpt.",
            "acceptedFilenameRegex": "^(.*)\\.(?:dpt)$",
	    "amStartArguments": "-n org.vita3k.emulator/org.vita3k.emulator.Emulator\n --esa AppStartParameters -r(?<!\\\\),{tags.game_id}",
            "killPackageProcesses": false,
            "killPackageProcessesWarning": true,
            "extra": ""
        }
    ]
}

**Comment by banzaibill7** [comment]
I'm having trouble launching Vita3k games from daijisho too. Ive updated the platform just now and changed the am start parameters for Vita3k as sugested. Using your dpt files too, but when I click to launch the games, the vita3k app just flashes and then ir returns to games list inside daijisho. Probably doing something wrong, could you help me?

**Comment by Jetup13** [comment]
Not sure what else to say but make sure your on the latest [Daijishou](https://github.com/TapiocaFox/Daijishou/releases/tag/v1.4.69) (1.4.69) and have updated the platform. 

https://github.com/user-attachments/assets/b96868c4-05e7-480b-828d-f3aa44186254

**Comment by jeferson-sb** [comment]
I also love the idea of having Custom collections, it could be something like a group in the widgets tabs

**Comment by davehartleyuk** [comment]
> Not sure what else to say but make sure your on the latest [Daijishou](https://github.com/TapiocaFox/Daijishou/releases/tag/v1.4.69) (1.4.69) and have updated the platform.
> 
>  file.1.mp4

I'm on Daijishou 1.4.69 (update via Obtanium so have got the most recent 2 updates)
Downloaded json file from : https://github.com/TapiocaFox/Daijishou/blob/main/platforms/SonyPSVita.json which says it was updated 18 hours ago.
Imported via library settings
Created 2 dpt files so games show in frontend.
Games are installed in vita3k and show in list and can be launched direct from vita3k.
But still get result in video...

https://github.com/user-attachments/assets/39d23707-bc17-44c0-8d5c-21698a8ff0f6

**Comment by Jetup13** [comment]
Hmm, are you using the correct dpt files? You can double-check by opening the dpt file with a notepad editor. Make sure the contents match the games title id. You can check the games title id via Vita3k.

**Comment by banzaibill7** [comment]
https://github.com/user-attachments/assets/4665efb3-e48c-4bbe-89da-dea4f500cd26

Checked the ID, apparently it's right

**Comment by Jetup13** [comment]
@banzaibill7 what device & what version of Daijishou your using?

> Daijishou > Settings > About

**Comment by banzaibill7** [comment]
The problem was the version. I was at 1.4.68, updated to 1.4.69 and now it's working. Using Odin 2 btw

**Comment by davehartleyuk** [comment]
Checked version: 1.4.69 (401)
Checked game number.
Checked dpt file matches game number.
Checked platform.
Still same issue. 
I'm at a loss, especially as other people are getting this working! :((

https://github.com/user-attachments/assets/a884065e-45a5-4d43-8235-9afd448e70c6

**Comment by davehartleyuk** [comment]
Sorted it! Finally got it working!

Although the dpt file looked right. There must have been an odd character or something. Deleting it and re-typing sorted it!

Thanks for the help!
