### ISSUE TITLE
Frontend doesnt recognise and rename roms

### ISSUE THREAD

**Issue by thomasmaruzs** [TapiocaFox/Daijishou#692]
Hi!

It would be great if the frontend would recognise and rename the Mame, CPS1, CPS2,CPS3 and Neogeo roms as did it in case of Final Burn roms. Currently the frontend shows the file names instead of the game name. In case of Final Burns roms its work great.
https://youtu.be/2Q4XetM3nl0

**Comment by Jetup13** [comment]
Daijishou Wiki: [Arcade Platforms not scraping](https://github.com/TapiocaFox/Daijishou/wiki/Frequently-Asked-Questions#arcade-platforms-not-scraping)
