### ISSUE TITLE
enormous amount of not installed emulators

### ISSUE THREAD

**Issue by b0ll3** [TapiocaFox/Daijishou#694]
Hey there

Daijishou shows me an enormous amount of emulators which aren't installed on my system (Anbernic RG Cube) and, as far as i know, never were.

Is there a way to get rid of them?
It's really annoying scrolling through like 500+ list entries to get to an preferred emulator

Best
Tim

**Comment by Jetup13** [comment]
Daijishou doesn't add players based on what you have installed. It adds what's in the platforms json file. You can remove players by:

> Daijishou > Settings > Library > Inspect Player's > Select player > Delete 

You can also do this via Platform edit page

If you don't like the players you can also create your own GitHub repo and use your own index.json/platforms

**Comment by b0ll3** [comment]
cool, thanks, will try that
