### ISSUE TITLE
(bug) Fast scrolling in list view for a system broken after last update

### ISSUE THREAD

**Issue by bigdumps42** [TapiocaFox/Daijishou#698]
on my rg556 I can no longer quickly scroll through games on a system in the list view using the back trigger buttons on my rg556, it still works in grid view but in list view both triggers will bring me to the top of the list instead of fast scrolling in either direction. I apologize for not tagging this properly, I don't know how to add a tag

**Comment by TapiocaFox** [comment]
Sorry could you send some pictures to or video for explanation. Thank you.

**Comment by bigdumps42** [comment]
> Sorry could you send some pictures to or video for explanation. Thank you.


https://github.com/user-attachments/assets/2491f96c-a61a-44a5-896e-088c3c4bda6b

**Comment by TapiocaFox** [comment]
Hey, thank you for the response. But I couldn't replicate the issue. And I believe. Are there any factors in your mind. Or weird messages in the logger?

https://github.com/user-attachments/assets/4a1d9f8a-5077-4b06-83e3-85934e8740a6

**Comment by bigdumps42** [comment]
> Hey, thank you for the response. But I couldn't replicate the issue. And I believe. Are there any factors in your mind. Or weird messages in the logger?
> trim.36429647-EC83-480D-8D45-DBA9110B55CA.MOV

nothing I can tell is weird in the logger, I tried rebinding the switching hotkeys to other buttons and the issue still persists. not sure what else to try

**Comment by Sp3eD541** [comment]
Commenting as the same issue is happening to me on my Odin 2.
The L1 and R1 buttons used to scroll through the alphabet while in the game list but after the update 2 days ago they no longer work while in the game list, they simply move my cursor all the way up to the very first game. 
the buttons still correctly work when scrolling through the platforms however.

**Comment by TapiocaFox** [comment]
Let me see if anything missing here.

**Comment by TapiocaFox** [comment]
Will be fixed in `1.4.71`.
