### ISSUE TITLE
Pin to Widget Problem

### ISSUE THREAD

**Issue by iifste2020** [TapiocaFox/Daijishou#704]
The pin option for a game only appears after you have already created a widget for that game. You can then pin multiple widgets of the same game. Using v402

**Comment by TapiocaFox** [comment]
I've tried mine but it works correctly in both library page and item details dialog. Pin item there only if the item is not pinned. Would you provide details a bit more? Did you disable merge item option?

**Comment by TapiocaFox** [comment]
Oh yes I can confirm merge item option breaks it.

**Comment by TapiocaFox** [comment]
Will be fixed in `1.4.71`.
