### ISSUE TITLE
Some game ROMs failed to import.

### ISSUE THREAD

**Issue by eziojay** [TapiocaFox/Daijishou#707]
For example, here are two arcade (FBN) game ROMs([dariusg.zip](https://github.com/user-attachments/files/16978904/dariusg.zip),[dariusgx.zip](https://github.com/user-attachments/files/16979060/dariusgx.zip)). I synchronized their paths, but only one of the games was imported into the library. I calculated the MD5 values for both: the MD5 of "dariusg.zip" is "186c84fcdf327111ce8863b7580fda95," and the MD5 of "dariusgx.zip" is "b2a63727ceda1e3570090c1fae1abe10." These are two distinct files, but I don’t understand why Daijishou ignores one of them.

I'm using Daijishou version 1.4.72.

**Comment by Jetup13** [comment]
Daijishou hashes the first 4MB if I remember correctly, not the full file. I just checked with a script and these two files do indeed match.

What can you do? Rezip one the files, this will certainly give you another md5 hash. Or use a different file extension for one.

**Comment by eziojay** [comment]
Thank you. I’ve tested ,Daijishou indeed calculate the first 4MB. I Rezip the files to solve the issue .But I still hope Daijishou can improve its hashing method to reduce conflicts and failed importing.
