### ISSUE TITLE
can't run in Dex. It's designed for phone Home Screens

### ISSUE THREAD

**Issue by python0test** [TapiocaFox/Daijishou#712]
I can't find a way to run it in Samsung DeX.
Is there a way to run it without the "Default home app" feature?

**Comment by TapiocaFox** [comment]
#128

**Comment by Marshy-Madness** [comment]
Enable dev mode in dex

**Comment by python0test** [comment]
This solution does not work on Android 14 and above.

**Comment by Marshy-Madness** [comment]
Does it work if you disable app compatibilty checks?

**Comment by python0test** [comment]
No i already try every option in developer-options
