### ISSUE TITLE
[Feature Request] Update ScummVM Wiki Entry

### ISSUE THREAD

**Issue by newhinton** [TapiocaFox/Daijishou#716]
Currently the wiki for scumm-vm only notes the .dpt files for the standalone app.
The retroarch-core requires a different file for the game to be recognized.

Could you add this information to the wiki?

Format:
```
filename: Gamename.scummvm
content: Gameid
```

Thank you!

**Comment by Jetup13** [comment]
Added to the [wiki](https://github.com/TapiocaFox/Daijishou/wiki/Players-and-File-Extensions#scummvm) with pregenerated scummvm files
