### ISSUE TITLE
[Feature Request] Ability to Add XBox Game Pass (or "Cloud Gaming") as Platform/Player (i.e. launch without needing a widget or shortcut)

### ISSUE THREAD

**Issue by foxonabox** [TapiocaFox/Daijishou#725]
Enhancement Idea: It would be nice to create a Platform for Game Pass (or other cloud game apps) so I can use the GORGEOUS Daijisho as my total device launcher, rather than retro only and then having to go to Apps or Widgets for xbox. 

Just a thought :)

**Comment by Jetup13** [comment]
Game Pass app doesn't support externally launching specific games unfortunately. Same as PlayStation Remote Play and Steam Link apps 

[Moonlight supports it on the otherhand](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#adding-moonlight-platform)
