### ISSUE TITLE
Rename "Strato" package name to work correctly

### ISSUE THREAD

**Issue by EZonTheEyes** [TapiocaFox/Daijishou#730]
In the current versions of DaiJiSho, the frontend is looking for a package named "strato.yosho" to run games. This is not the naming convention we will be releasing Strato under, and is incorrect. Please update this to "org.stratoemu.strato" for Strato support.

**Comment by Jetup13** [comment]
[7f2e011](https://github.com/TapiocaFox/Daijishou/commit/7f2e011974fe684effee1ff59f950227551abba1)

Try now. I added what I assume is the correct am start. 

Update the Switch platform to latest for the new `switch - Strato (Official)` player

**Comment by EZonTheEyes** [comment]
issue resolved now, thank you!

> [7f2e011](https://github.com/TapiocaFox/Daijishou/commit/7f2e011974fe684effee1ff59f950227551abba1)
> 
> Try now. I added what I assume is the correct am start.
> 
> Update the Switch platform to latest for the new `switch - Strato (Official)` player
