### ISSUE TITLE
No infinity Pico 8 emulator option in player setting

### ISSUE THREAD

**Issue by Certifr1ed** [TapiocaFox/Daijishou#731]
Would It be possible to add the standalone android Pico 8 emulator infinity on the player settings as an option?
Would like to open my Pico 8 games from daijisho frontend.

**Comment by Jetup13** [comment]
I believe this can be added. Seems like they have an activity to allow it. I'm away from computer but if you want to try it [add this as a player](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#adding-players):

Player Name:

```
pico8 - Infinity
``` 

Player am start:

```
-n me.dt2dev.infinity/me.dt2dev.infinity.SchemeActivity
-a android.intent.action.VIEW
-d {file.uri}
```

Player filename regex:

```
"^(.*)\\.(?:p8|png)$"
```

**Comment by Jetup13** [comment]
Added in [8ddd95b](https://github.com/TapiocaFox/Daijishou/commit/8ddd95b5a1aede6c84356b510aa3376e98d5b8b3). Update the pico8 platform

**Comment by Certifr1ed** [comment]
So update Pico 8 infinity or daijisho?

**Comment by Jetup13** [comment]
Neither, [update the platform](https://github.com/TapiocaFox/Daijishou/wiki/How-to-Use-Daijish%C5%8D#updating-platforms)

**Comment by Certifr1ed** [comment]
@Jetup13 works good now thanks
