### ISSUE TITLE
Latest update killed the Daijishou on my Odin 2 Pro

### ISSUE THREAD

**Issue by TinfoilDurag** [TapiocaFox/Daijishou#740]
Launches, but crashes during load with "Daijisho keeps stopping". Cleared cache, even uninstalled and reinstalled. Same result.

**Comment by NiKo-OnGit** [comment]
I'm on the same boat on a Retroid Pocket 5

**Comment by fabinhojcr** [comment]
The same thing is happening on my powkiddy x28.

**Comment by Jetup13** [comment]
Seems like the crash is related to the extension manager? Or at least it seems to crash on startup right around there @TapiocaFox

**Comment by fabinhojcr** [comment]
In my case, the crash occurs at startup. @Jetup13

**Comment by TapiocaFox** [comment]
Sorry for the troubles. Would you mind send me the crash logs if possible?

**Comment by TapiocaFox** [comment]
Nvm. Like @Jetup it was the extension features that messed it up. I will release the latest build ASAP.

**Comment by TapiocaFox** [comment]
Please try [v1.4.78](https://github.com/TapiocaFox/Daijishou/releases/tag/v1.4.78)

**Comment by fabinhojcr** [comment]
Problem solved.
