### ISSUE TITLE
Request: Add .Wux Support for Wii U Platform

### ISSUE THREAD

**Issue by reianayami** [TapiocaFox/Daijishou#742]
.Wux games don't show up when adding my Wii U folder, due to only .rpx, .wua being supported

**Comment by Jetup13** [comment]
Correct, Cemu on android only supports `.rpx` & `.wua`. 

[Cemu Android FAQ](https://rentry.org/cemu-android)

> Q: What file formats does Cemu for Android support?

```
A: It supports .wua and extracted format ("RPX format"). .wux and .wud formats are not currently supported. Note that piracy is strictly forbidden and we ask you to get your games legally by following the [official guide](https://cemu.cfw.guide/dumping-games.html).
```

**Comment by reianayami** [comment]
> Correct, Cemu on android only supports `.rpx` & `.wua`.
> 
> [Cemu Android FAQ](https://rentry.org/cemu-android)
> 
> > Q: What file formats does Cemu for Android support?
> 
> ```
> A: It supports .wua and extracted format ("RPX format"). .wux and .wud formats are not currently supported. Note that piracy is strictly forbidden and we ask you to get your games legally by following the [official guide](https://cemu.cfw.guide/dumping-games.html).
> ```

It definitely supports wux format on Android. That must not be up to date. All my games are wux and work fine

here’s a video of someone doing it when it was released also 
https://youtu.be/TMwNk21cClg?si=Fy-6qpl8Ra5NYdef

**Comment by Jetup13** [comment]
Ah I see so Cemu reads a keys.txt files which has a list of decryption keys needed for each game. I'll update the platform. I removed your link since it has links to a piracy group

**Comment by reianayami** [comment]
> Ah I see so Cemu reads a keys.txt files which has a list of decryption keys needed for each game. I'll update the platform. I removed your link since it has links to a piracy group

Thank you so much! Sorry about that I was unaware, my fault.
